--[[

	The MIT License (MIT)

	Copyright (c) 2026 Jonas "JuNNeZ" Andersen

--]]
-- Generated by Tools/BuildChangelog.lua. Do not edit by hand.
--
-- The 1 most recent releases of 1 in CHANGELOG.md, which stays the
-- source of truth. Regenerate after editing it:
--
--     lua Tools/BuildChangelog.lua
local Addon, ns = ...

ns.Changelog = {
	{
		version = "9.9.9-Test",
		date = "2026-01-02",
		title = "A Bold Title",
		groups = {
			{
				kind = "Fixed",
				items = {
					"Bold lead. Body with italics, a code span and a link, continued on a second line.",
					"A plain note.",
				},
			},
			{
				kind = "Internal",
				items = {
					"Another one.",
				},
			},
		},
	},
}

-- Everything older is in CHANGELOG.md.
ns.ChangelogTotal = 1
