-- In-memory mutations: never edits addon files or the working tree.
-- lua Tools/Harness/mutate_client.lua .
local root = arg[1] or "."
local originalLoadfile = loadfile
local cases = {
	{"client detection", "Core/Client.lua", "ns.Private.IsForever = forever and true or false", "ns.Private.IsForever = false"},
	{"modern engine", "Core/Client.lua", "ns.Private.IsRetail = ns.Private.IsMainline", "ns.Private.IsRetail = false"},
	{"API aliases", "Core/Compatibility.lua", "if (C_Spell and C_SpellBook and C_Reputation) then", "if (false) then"},
	{"secret tuple", "Core/Compatibility.lua", "local hasSecretValues = ns.HasSecretValues", "local hasSecretValues = false"},
	{"arena gate", "Components/UnitFrames/Units/Arena.lua", "if (ns.IsForever) then return end", ""},
	{"arena bootstrap", "WoW11/UnitFrames/ArenaFrames.lua", "not ns.WoW11 or ns.IsForever", "not ns.WoW11"},
	{"inspect gate", "Components/UnitFrames/GroupSpecCache.lua", "ticker or ns.IsForever or", "ticker or"},
	{"class resource gate", "Libs/oUF/elements/classpower.lua", "if(ns.IsForever and playerClass", "if(false and playerClass"},
	{"menu game rules", "Components/ActionBars/Elements/MicroMenu.lua", "and not disabled and not", "and not"},
	{"menu callbacks", "Components/ActionBars/Elements/MicroMenu.lua", "info.callback and info.callback()", "false"},
	{"event validation", "Libs/oUF/private.lua", "return C_EventUtils.IsEventValid(event)", "return true"},
	{"snippet probe", "Core/Client.lua", "\treturn ran\nend", "\treturn true\nend"},
	-- Without the pcall the error escapes and takes the rest of Core/Client.lua with
	-- it, which is exactly what happened on Forever 1.60.1.69913.
	{"snippet probe containment", "Core/Client.lua",
		'pcall(probe.SetAttribute, probe, "state-azsnippetprobe", "run")',
		'probe:SetAttribute("state-azsnippetprobe", "run")'},
	{"snippet probe scope", "Core/Client.lua",
		'if (not isAddOnLoaded("Blizzard_RestrictedAddOnEnvironment")) then return true end',
		'if (false) then return true end'},
	{"Forever probe bypass", "Core/Client.lua", "if (forever) then", "if (false) then"},
	{"numeric page driver", "Components/ActionBars/Prototypes/ActionBar.lua",
		"statedriver = BuildConditionalDriver(conditions, fallback, function(page) return page end)", ""},
	{"per-button action driver", "Components/ActionBars/Prototypes/ActionBar.lua",
		"\t\tself:UpdateActionDrivers()", ""},
	{"native visibility driver", "Components/ActionBars/Prototypes/ActionBar.lua",
		'API.RegisterVisibilityDriver(self, visdriver or "hide")', ""},
	{"non-paging bar guard", "Components/ActionBars/Prototypes/ActionBar.lua",
		"\tif (not conditions) then return end", ""},
	-- An entry whose native button Blizzard has gated must grey out, or it looks
	-- live and swallows the press - which is how Talents and Legacy read at level 1.
	{"micro menu gating", "Components/ActionBars/Elements/MicroMenu.lua",
		"local usable = IsNativeButtonUsable(button.ref)", "local usable = true"},
	-- Trusting a cache from another build would keep a stale "available" answer
	-- across the very patch that changed it.
	{"snippet cache build match", "Core/Client.lua",
		"cached.build == currentBuild and ", ""},
	-- Forever combo points are secret; each break below leaves them invisible or throws.
	{"secret point fill", "Libs/oUF/elements/classpower.lua",
		"element[i]:SetValue(cur)\n", "", "combo_points_harness.lua"},
	{"secret max fallback", "Libs/oUF/elements/classpower.lua",
		"(IsSecretValue and IsSecretValue(max)) or max <= 0",
		"(not (IsSecretValue and IsSecretValue(max)) and max <= 0)", "combo_points_harness.lua"},
	{"secret range restore", "Libs/oUF/elements/classpower.lua",
		"element[i]:SetMinMaxValues(0, 1)", "", "combo_points_harness.lua"},
	{"secret hide at zero", "Components/UnitFrames/Units/PlayerClassPower.lua",
		"hideAtZero and not isSecretCur and cur <= 0", "hideAtZero and cur <= 0", "combo_points_harness.lua"},
	{"secret point alpha", "Components/UnitFrames/Units/PlayerClassPower.lua",
		"elseif (isSecretCur) then", "elseif (false) then", "combo_points_harness.lua"},
	{"secret full fade option", "Components/UnitFrames/Units/PlayerClassPower.lua",
		"not element.inCombat and not showFullOutOfCombat)", "not element.inCombat)", "combo_points_harness.lua"},
	{"secret empty socket", "Components/UnitFrames/Units/PlayerClassPower.lua",
		"curve:AddPoint(.5 / max, .5)", "", "combo_points_harness.lua"},
	{"secret half-step threshold", "Components/UnitFrames/Units/PlayerClassPower.lua",
		"curve:AddPoint((index - .5) / max, 1)", "curve:AddPoint(index / max, 1)", "combo_points_harness.lua"},
	{"secret path Forever only", "Libs/oUF/elements/classpower.lua",
		"local isSecretCur = GetTargetComboPoints and (type(cur)", "local isSecretCur = (type(cur)",
		"combo_points_harness.lua"},
	-- Hide the Blizzard Tracker. The tracker is hidden by alpha, so anything that asserts
	-- the alpha instead of deriving it shows a tracker the player switched off.
	{"tracker alpha at prepare", "Components/Misc/TrackerWoW11.lua",
		"SetClampedToScreen(false)\n\tUpdateTrackerAlpha()",
		"SetClampedToScreen(false)\n\tObjectiveTrackerFrame:SetAlpha(.9)", "tracker_harness.lua"},
	{"tracker alpha on events", "Components/Misc/TrackerWoW11.lua",
		"event == \"SETTINGS_LOADED\") then\n\t\tself:UpdateSettings()",
		"event == \"SETTINGS_LOADED\") then\n\t\tself:UpdateSettings()\n\t\tObjectiveTrackerFrame:SetAlpha(.9)",
		"tracker_harness.lua"},
	{"tracker alpha re-derived on settings", "Components/Misc/TrackerWoW11.lua",
		"\tself:UpdateAutoHideDriver()\n\tUpdateTrackerAlpha()\nend", "\tself:UpdateAutoHideDriver()\nend",
		"tracker_harness.lua"},
	{"tracker hider OnHide", "Components/Misc/TrackerWoW11.lua",
		"SetScript(\"OnHide\", UpdateTrackerAlpha)", "SetScript(\"OnHide\", function() end)", "tracker_harness.lua"},
	-- The Retail break that shipped: the setting never reached the driver.
	{"tracker Retail driver folds the setting", "Components/Misc/TrackerWoW11.lua",
		"RegisterStateDriver(autoHider, \"vis\", driver)",
		"RegisterStateDriver(autoHider, \"vis\", GetAutoHideDriver())", "tracker_harness.lua"},
	{"tracker Forever driver folds the setting", "Components/Misc/TrackerWoW11.lua",
		"RegisterVisibilityDriver(autoHider, driver)",
		"RegisterVisibilityDriver(autoHider, GetAutoHideDriver())", "tracker_harness.lua"},
	{"tracker driver combat deferral", "Components/Misc/TrackerWoW11.lua",
		"\tif (InCombatLockdown()) then\n\t\tself:QueueCombatRefresh()\n\t\treturn false\n\tend\n\n\tlocal disabled",
		"\tlocal disabled", "tracker_harness.lua"},
	{"tracker combat refresh applies", "Components/Misc/TrackerWoW11.lua",
		"self:PrepareFrames()\n\t\t\tself:UpdateSettings()", "self:PrepareFrames()", "tracker_harness.lua"},
	{"tracker combat refresh unregisters", "Components/Misc/TrackerWoW11.lua",
		"self:UnregisterEvent(\"PLAYER_REGEN_ENABLED\", \"OnEvent\")", "", "tracker_harness.lua"},
	{"tracker snippet gate", "Components/Misc/TrackerWoW11.lua",
		"local hasSecureSnippets = ns.HasSecureSnippets ~= false", "local hasSecureSnippets = true",
		"tracker_harness.lua"},
	{"tracker Immersion open", "Components/Misc/TrackerWoW11.lua",
		" or (ImmersionFrame and ImmersionFrame:IsShown())", "", "tracker_harness.lua"},
	{"tracker Immersion close", "Components/Misc/TrackerWoW11.lua",
		"SecureHookScript(ImmersionFrame, \"OnHide\", UpdateTrackerAlpha)",
		"SecureHookScript(ImmersionFrame, \"OnHide\", function() ObjectiveTrackerFrame:SetAlpha(.9) end)",
		"tracker_harness.lua"},
	-- Locales. A missing key falls back to English; a moved specifier formats the wrong value,
	-- or raises, because Lua 5.1's string.format has no positional arguments.
	{"locale missing key", "Locale/deDE.lua",
		"L[\"Search settings\"] = \"Einstellungen durchsuchen\"", "", "locale_harness.lua"},
	{"locale specifier order", "Locale/deDE.lua",
		"\"%d von %d Einstellungen\"", "\"%s von %d Einstellungen\"", "locale_harness.lua"},
	{"locale duplicate key", "Locale/frFR.lua",
		"L[\"Not bound\"] = \"Non assigné\"",
		"L[\"Not bound\"] = \"Non assigné\"\nL[\"Not bound\"] = \"Non assigné\"", "locale_harness.lua"},
	{"locale empty value", "Locale/zhCN.lua", "= \"搜索设置\"", "= \"\"", "locale_harness.lua"},
	{"locale explanation width", "Locale/deDE.lua", "= \"Gilt für alle Aktionsleisten.\"",
		"= \"Gilt für jede einzelne Aktionsleiste, die AzeriteUI zeichnet, und für alle ihre Tasten.\"",
		"locale_harness.lua"},
	{"locale tab width", "Locale/ruRU.lua", "L[\"Options\"] = \"Параметры\"",
		"L[\"Options\"] = \"Параметры интерфейса\"", "locale_harness.lua"},
	-- Nameplates (Phase 0). Each break is one of the behaviours the overhaul must keep.
	{"nameplate object overlay", "Components/UnitFrames/NamePlates/Visibility.lua",
		"return (self.isSoftTarget or self.isMouseOver or self.isTarget) and true or false",
		"return false", "nameplate_harness.lua"},
	{"nameplate name-only anchor", "Components/UnitFrames/NamePlates/Visibility.lua",
		"self.Name:SetPoint(\"BOTTOM\", self:GetParent() or self, \"BOTTOM\", x, FRIENDLY_NAME_ONLY_NAME_OFFSET_Y)",
		"self.Name:SetPoint(unpack(db.NamePosition))", "nameplate_harness.lua"},
	{"nameplate locked cast grey", "Components/UnitFrames/NamePlates/Castbar.lua",
		"\tif (state == \"locked\") then\n\t\tNamePlate_SetCastbarColor(element, Colors.gray)",
		"\tif (state == \"locked\") then\n\t\tNamePlate_SetCastbarColor(element, color)", "nameplate_harness.lua"},
	{"nameplate target scale", "Components/UnitFrames/NamePlates/Settings.lua",
		"\t\t\tscale = scale * (1 + GetEnemyNamePlateTargetScaleSetting())", "", "nameplate_harness.lua"},
	-- The dungeon's alpha lives in the content settings' defaults since Phase 6.
	{"nameplate dungeon alpha", "Components/UnitFrames/NamePlates/Settings.lua",
		"dungeon = { minAlpha = .75,", "dungeon = { minAlpha = .5,", "nameplate_harness.lua"},
	-- 2026-09-24: auras through the native container, and a raid marker that stays put. (A4's aura-row
	-- lift went with it: the container keeps its size secret, so there are no rows to count.)
	{"nameplate raid marker beside the bar", "Components/UnitFrames/NamePlates/Elements.lua",
		"raidTarget:SetPoint(point, self.Health, relativePoint, x, y)", "raidTarget:SetPoint(point, self, relativePoint, x, y)",
		"nameplate_harness.lua"},
	{"nameplate raid marker default size", "Components/UnitFrames/NamePlates/Elements.lua",
		"raidTarget:SetSize(size, size)", "raidTarget:SetSize(64, 64)", "nameplate_harness.lua"},
	{"nameplate raid marker follows its setting", "Components/UnitFrames/NamePlates/Elements.lua",
		"if (raidTarget.__AzeriteUI_Size == size and raidTarget.__AzeriteUI_NameOnly == nameOnly) then",
		"if (raidTarget.__AzeriteUI_Size ~= nil) then", "nameplate_harness.lua"},
	{"nameplate native auras", "Components/UnitFrames/NamePlates/Visibility.lua",
		"local native = shown and EnsureNamePlateNativeAuras(self) or self.NativeAuras", "local native = nil",
		"nameplate_harness.lua"},
	{"nameplate auras kept in combat", "Components/UnitFrames/NamePlates/Layout.lua",
		"SetNamePlateAurasShown(self, profile.showAuras and (not profile.showAurasOnTargetOnly or self.isTarget),",
		"SetNamePlateAurasShown(self, profile.showAuras and not self.inCombat and (not profile.showAurasOnTargetOnly or self.isTarget),",
		"nameplate_harness.lua"},
	{"nameplate recycled container", "Components/UnitFrames/NamePlates/Visibility.lua",
		"rebuild and native.displayEnabled", "false", "nameplate_harness.lua"},
	{"nameplate scanning fallback", "Components/UnitFrames/NamePlates/Visibility.lua",
		"\tif (shown) then\n\t\tif (not self:IsElementEnabled(\"Auras\")) then", "\tif (false) then\n\t\tif (true) then",
		"nameplate_harness.lua"},
	{"nameplate aura group filters", "Components/UnitFrames/Auras/PlayerAuraContainers.lua",
		"return { excludeSpellIDs = HiddenAuras, nameplateShowAll = true }", "return { excludeSpellIDs = HiddenAuras, nameplateShowALL = true }",
		"nameplate_harness.lua"},
	-- Phase 5: one interrupt resolver (Interrupts.lua), asked by the plates and the target castbar.
	{"nameplate plates ask the resolver", "Components/UnitFrames/NamePlates/Castbar.lua",
		"local interruptSpellID, interruptReady = ns.API.GetPrimaryInterrupt()",
		"local interruptSpellID, interruptReady = nil, nil", "nameplate_harness.lua"},
	{"interrupt duration object first", "Components/UnitFrames/Interrupts.lua",
		"local ready = ReadyFromDuration(queryID)", "local ready = nil", "nameplate_harness.lua"},
	{"interrupt pet casts seen", "Components/UnitFrames/Interrupts.lua",
		"listener:RegisterUnitEvent(\"UNIT_SPELLCAST_SUCCEEDED\", \"player\", \"pet\")",
		"listener:RegisterUnitEvent(\"UNIT_SPELLCAST_SUCCEEDED\", \"player\")", "nameplate_harness.lua"},
	{"interrupt sacrifice requirement", "Components/UnitFrames/Interrupts.lua",
		"if (not requirement or requirement()) then", "if (true) then", "nameplate_harness.lua"},
	{"interrupt Forever ranks", "Components/UnitFrames/Interrupts.lua",
		"\tif (ns.IsForever) then\n\t\treturn FOREVER_SPELLS, FOREVER_COOLDOWNS", "\tif (false) then\n\t\treturn FOREVER_SPELLS, FOREVER_COOLDOWNS",
		"nameplate_harness.lua"},
	{"interrupt ignores the global cooldown", "Components/UnitFrames/Interrupts.lua",
		"API.TryCall(C_Spell.GetSpellCooldownDuration, spellID, true)", "API.TryCall(C_Spell.GetSpellCooldownDuration, spellID)",
		"nameplate_harness.lua"},
	-- Phase 6: content settings.
	{"nameplate content alpha", "Components/UnitFrames/NamePlates/CVars.lua",
		"return GetContentSetting(contentType, \"minAlpha\"), GetContentSetting(contentType, \"occludedAlpha\")",
		"return .4, .15", "nameplate_harness.lua"},
	{"nameplate content distance", "Components/UnitFrames/NamePlates/Settings.lua",
		"return GetContentSetting(GetCurrentContentType(), \"maxDistance\")", "return 40", "nameplate_harness.lua"},
	{"nameplate Mythic+ detected", "Components/UnitFrames/NamePlates/Settings.lua",
		"\t\treturn \"mythicplus\"\n", "\t\treturn \"dungeon\"\n", "nameplate_harness.lua"},
	{"nameplate key events", "Components/UnitFrames/NamePlates/Module.lua",
		"\t\t-- A key starting or ending turns a dungeon into Mythic+ and back without a loading screen.\n\t\tApplyNamePlateDriverSettings(self)",
		"", "nameplate_harness.lua"},
	{"nameplate distance migration", "Components/UnitFrames/NamePlates/Module.lua",
		"\t\t\t\tself.db.profile.contentSettings[contentType].maxDistance = distance\n", "", "nameplate_harness.lua"},
	-- Phase 7: the combat filter.
	{"nameplate combat filter spares the target", "Components/UnitFrames/NamePlates/Visibility.lua",
		"and not (self.isTarget or self.isFocus", "and not (self.isFocus", "nameplate_harness.lua"},
	{"nameplate combat filter asks the group", "Components/UnitFrames/NamePlates/Visibility.lua",
		"\t\tif (IsOnThreatTable(units[index], unit) or IsOnThreatTable(pets[index], unit)) then",
		"\t\tif (false) then", "nameplate_harness.lua"},
	{"nameplate combat filter secret threat", "Components/UnitFrames/NamePlates/Visibility.lua",
		"\tif (IsSecretValue(status)) then\n\t\treturn true", "\tif (IsSecretValue(status)) then\n\t\treturn false",
		"nameplate_harness.lua"},
	{"nameplate combat filter timer off", "Components/UnitFrames/NamePlates/Module.lua",
		"if (self.db.profile.combatFilter and self:IsEnabled()) then", "if (self:IsEnabled()) then", "nameplate_harness.lua"},
	{"nameplate hidden plate under a UIParent fade", "Components/UnitFrames/NamePlates/Visibility.lua",
		"\tif (not self.__AzeriteUI_AlphaHidden) then\n\t\talpha = UIParent:GetAlpha()",
		"\tdo\n\t\talpha = UIParent:GetAlpha()", "nameplate_harness.lua"},
	-- Phase 8: the execute marker.
	{"nameplate execute marker built lazily", "Components/UnitFrames/NamePlates/Elements.lua",
		"\tif (not show) then\n\t\tif (marker and marker.isShown) then",
		"\tmarker = marker or CreateExecuteMarker(self)\n\tif (not show) then\n\t\tif (marker and marker.isShown) then",
		"nameplate_harness.lua"},
	{"nameplate execute marker on enemies only", "Components/UnitFrames/NamePlates/Elements.lua",
		"local show = threshold > 0 and self.canAttack and not self.isPRD", "local show = threshold > 0 and not self.isPRD",
		"nameplate_harness.lua"},
	{"nameplate execute line from the empty end", "Components/UnitFrames/NamePlates/Elements.lua",
		"local width = db.HealthBarSize[1] * threshold", "local width = db.HealthBarSize[1] * (1 - threshold)",
		"nameplate_harness.lua"},
	{"nameplate execute line mirrors", "Components/UnitFrames/NamePlates/Elements.lua",
		"local edge = reverse and \"RIGHT\" or \"LEFT\"", "local edge = \"LEFT\"", "nameplate_harness.lua"},
	{"nameplate execute tint below the threshold", "Components/UnitFrames/NamePlates/Elements.lua",
		"curve:AddPoint(0, 1)\n\t\t\tcurve:AddPoint(threshold, 0)", "curve:AddPoint(0, 0)\n\t\t\tcurve:AddPoint(threshold, 1)",
		"nameplate_harness.lua"},
	{"nameplate execute health as it is", "Components/UnitFrames/NamePlates/Elements.lua",
		"UnitHealthPercent, self.unit, false, curve", "UnitHealthPercent, self.unit, true, curve", "nameplate_harness.lua"},
	{"nameplate execute tint on health updates", "Components/UnitFrames/NamePlates/Elements.lua",
		"\t\tpredict:ForceUpdate()\n\tend\n\tUpdateExecuteZone(element.__owner)", "\t\tpredict:ForceUpdate()\n\tend",
		"nameplate_harness.lua"},
	{"nameplate execute hidden tint left alone", "Components/UnitFrames/NamePlates/Elements.lua",
		"\tif (not marker or not marker.isShown) then\n\t\treturn\n\tend\n\tlocal alpha = 0",
		"\tif (not marker) then\n\t\treturn\n\tend\n\tlocal alpha = 0", "nameplate_harness.lua"},
	{"nameplate execute hides its textures", "Components/UnitFrames/NamePlates/Elements.lua",
		"\t\t\tmarker.isShown = false\n\t\t\tmarker.Line:Hide()\n\t\t\tmarker.Zone:Hide()", "\t\t\tmarker.isShown = false",
		"nameplate_harness.lua"},
	{"nameplate execute follows the class", "Components/UnitFrames/NamePlates/Module.lua",
		"\t\t\tfor plate in next, ns.ActiveNamePlates do\n\t\t\t\tUpdateExecuteMarker(plate)\n\t\t\tend\n", "",
		"nameplate_harness.lua"},
	{"nameplate execute threshold held to half", "Components/UnitFrames/NamePlates/Settings.lua",
		"return (custom > EXECUTE_THRESHOLD_MAX) and EXECUTE_THRESHOLD_MAX or custom", "return custom",
		"nameplate_harness.lua"},
	{"nameplate execute talent gate", "Components/UnitFrames/ExecuteRange.lua",
		"(not entry.spell or (isKnown and isKnown(entry.spell)))", "true", "nameplate_harness.lua"},
	-- Phase 9: plays nice.
	{"nameplate stands down for Platynator", "Components/UnitFrames/NamePlates/Module.lua",
		"\t\t\"Platynator\",\n", "", "nameplate_harness.lua"},
	{"nameplate stand-down writes no CVars at login", "Components/UnitFrames/NamePlates/Module.lua",
		"\t-- Check for conflicts with other nameplate addons\n",
		"\tApplyFriendlyNameOnlyCVars()\n\t-- Check for conflicts with other nameplate addons\n", "nameplate_harness.lua"},
	{"nameplate stand-down is not an enabled change", "Components/UnitFrames/NamePlates/Module.lua",
		"local shouldBeEnabled = self.db.profile.enabled and not self.conflictingAddOn",
		"local shouldBeEnabled = self.db.profile.enabled", "nameplate_harness.lua"},
	{"nameplate settings write CVars only when in charge", "Components/UnitFrames/NamePlates/Module.lua",
		"\telseif (isCurrentlyEnabled) then\n\t\t-- Only while these plates are in charge; otherwise the CVars belong to whoever is.\n\t\tApplyFriendlyNameOnlyCVars()",
		"\telse\n\t\tApplyFriendlyNameOnlyCVars()", "nameplate_harness.lua"},
	-- Aura filters and the stacking passthrough.
	{"nameplate aura kind switched off", "Components/UnitFrames/Auras/PlayerAuraContainers.lua",
		"container:SetAuraGroupMaxFrameCount(group.key, filter and config.maxAuras or 0)",
		"container:SetAuraGroupMaxFrameCount(group.key, config.maxAuras)", "nameplate_harness.lua"},
	{"nameplate aura kinds disjoint", "Components/UnitFrames/Auras/PlayerAuraContainers.lua",
		"exclude = function(config) return config.showCrowdControl and \"CROWD_CONTROL\" or nil end,\n\t\tcandidates",
		"candidates", "nameplate_harness.lua"},
	{"nameplate aura kinds built lazily", "Components/UnitFrames/Auras/PlayerAuraContainers.lua",
		"local filter = config[group.shownField] and GetNamePlateGroupFilter(group, config) or nil",
		"local filter = GetNamePlateGroupFilter(group, config)", "nameplate_harness.lua"},
	{"nameplate aura filters catch up", "Components/UnitFrames/NamePlates/Visibility.lua",
		"if (shown and native.__AzeriteUI_ConfigVersion ~= GetNamePlateAuraConfigVersion()) then", "if (false) then",
		"nameplate_harness.lua"},
	{"nameplate stacking waits for combat", "Components/UnitFrames/NamePlates/CVars.lua",
		"\tif (InCombatLockdown()) then\n\t\tself.pendingStacking", "\tif (false) then\n\t\tself.pendingStacking",
		"nameplate_harness.lua"},
	{"nameplate stacking applied after combat", "Components/UnitFrames/NamePlates/Module.lua",
		"\t\tApplyPendingNamePlateStacking(self)\n", "", "nameplate_harness.lua"},
	-- Phase 2's fixes, each put back the way it was.
	{"nameplate watcher refresh (A5)", "Components/UnitFrames/NamePlates/Castbar.lua",
		"\nCastbar_RefreshInterruptVisuals = function(element)", "\nlocal Castbar_RefreshInterruptVisuals = function(element)",
		"nameplate_harness.lua"},
	{"nameplate zone alpha in the driver (A8)", "Components/UnitFrames/NamePlates/CVars.lua",
		"values[\"nameplateMinAlpha\"], values[\"nameplateOccludedAlphaMult\"] = GetZoneAlphaCVars()", "",
		"nameplate_harness.lua"},
	{"nameplate second pass (A2)", "Components/UnitFrames/NamePlates/Module.lua",
		"self.unit == unit and NamePlate_NeedsSecondPass(self, unit)", "false", "nameplate_harness.lua"},
	-- Phase 3's event model, each piece put back the way it was.
	{"nameplate target laid out once (A3)", "Components/UnitFrames/NamePlates/Module.lua",
		"if (plate.isTarget and not SafeUnitMatches(unit, \"target\")) then\n\t\t\t\tplate.isTarget = false",
		"if (plate.isTarget or SafeUnitMatches(unit, \"target\")) then\n\t\t\t\tplate.isTarget = SafeUnitMatches(unit, \"target\")",
		"nameplate_harness.lua"},
	{"nameplate focus touches its plate only (C1)", "Components/UnitFrames/NamePlates/Module.lua",
		"if (isFocus ~= (plate.isFocus and true or false)) then", "if (true) then", "nameplate_harness.lua"},
	{"nameplate hover poll stops (C2)", "Components/UnitFrames/NamePlates/Module.lua",
		"\t\t\tNamePlatesMod:CancelTimer(NamePlatesMod.mouseTimer)\n\t\t\tNamePlatesMod.mouseTimer = nil\n", "",
		"nameplate_harness.lua"},
	{"nameplate hover moves between plates (C2)", "Components/UnitFrames/NamePlates/Module.lua",
		"\t\tNamePlate_OnLeave(MOUSEOVER)\n\t\tMOUSEOVER = nil\n\tend\n\tfor frame", "\t\tMOUSEOVER = nil\n\tend\n\tfor frame",
		"nameplate_harness.lua"},
	{"nameplate zone change lays out nothing", "Components/UnitFrames/NamePlates/Module.lua",
		"if (isInitialLogin or isReloadingUi) then", "if (true) then", "nameplate_harness.lua"},
	{"nameplate target shows its name (A9)", "Components/UnitFrames/NamePlates/Layout.lua",
		"\tif (self.Castbar) then\n\t\tCastbar_PostUpdate(self.Castbar)",
		"\tif (self.Castbar and event ~= \"PLAYER_TARGET_CHANGED\") then\n\t\tCastbar_PostUpdate(self.Castbar)",
		"nameplate_harness.lua"},
	{"nameplate focus outline", "Components/UnitFrames/NamePlates/Elements.lua",
		"self.isFocus and element.colorFocus or element.colorTarget", "element.colorTarget", "nameplate_harness.lua"},
	{"nameplate widget container", "Components/UnitFrames/NamePlates/Layout.lua",
		"\t\t\tif (NamePlatesMod.db.profile.showBlizzardWidgets) then\n\t\t\t\tUpdateNamePlateWidgetContainer(self, true)\n\n\t\t\t\tlocal widgetFrames = self.WidgetContainer.widgetFrames\n\n\t\t\t\tif (widgetFrames) then\n\t\t\t\t\tfor _, frame in next, widgetFrames do\n\t\t\t\t\t\tif (frame.Label) then\n\t\t\t\t\t\t\tframe.Label:SetAlpha(0)\n\t\t\t\t\t\tend\n\t\t\t\t\tend\n\t\t\t\tend\n\t\t\telse\n\t\t\t\tUpdateNamePlateWidgetContainer(self, false)\n\t\t\tend\n\t\tend\n\n\t\tif (self.isMouseOver",
		"\t\t\tUpdateNamePlateWidgetContainer(self, false)\n\t\tend\n\n\t\tif (self.isMouseOver", "nameplate_harness.lua"}
}
local function harnessFor(case)
	return root .. "/Tools/Harness/" .. (case[5] or "client_harness.lua")
end
assert(originalLoadfile(root .. "/Tools/Harness/client_harness.lua"))()
assert(originalLoadfile(root .. "/Tools/Harness/combo_points_harness.lua"))()
assert(originalLoadfile(root .. "/Tools/Harness/tracker_harness.lua"))()
assert(originalLoadfile(root .. "/Tools/Harness/locale_harness.lua"))()
assert(originalLoadfile(root .. "/Tools/Harness/nameplate_harness.lua"))()
for _, case in ipairs(cases) do
	local mutations = 0
	loadfile = function(path)
		if path:sub(-#case[2]) ~= case[2] then return originalLoadfile(path) end
		local file = assert(io.open(path, "r"))
		local source = file:read("*a")
		file:close()
		local first, last = source:find(case[3], 1, true)
		assert(first, "mutation target missing: " .. case[1])
		mutations = mutations + 1
		return loadstring(source:sub(1, first - 1) .. case[4] .. source:sub(last + 1), "@" .. path)
	end
	local ok, err = pcall(assert(originalLoadfile(harnessFor(case))))
	loadfile = originalLoadfile
	assert(mutations > 0, "mutation was not applied: " .. case[1])
	assert(not ok, "mutation survived: " .. case[1])
	print("Caught " .. case[1] .. ": " .. tostring(err))
end
print("Client mutations: " .. #cases .. " caught; no files modified")
