--[[

	The MIT License (MIT)

	Copyright (c) 2026 Jonas "JuNNeZ" Andersen

--]]
-- Generated by Tools/BuildChangelog.lua. Do not edit by hand.
--
-- The 12 most recent releases of 28 in CHANGELOG.md, which stays the
-- source of truth. Regenerate after editing it:
--
--     lua Tools/BuildChangelog.lua
local Addon, ns = ...

ns.Changelog = {
	{
		version = "5.12.0-JuNNeZ",
		date = "2026-09-26",
		title = "Mythic+ Timer, Great Vault, Pandemic Timers, and Dragging Back on Forever",
		groups = {
			{
				kind = "Highlights",
				items = {
					"A Mythic+ timer. A new frame shows the running key: dungeon and level, a timer bar with marks where the +3 and +2 upgrades run out, how long you have left for the next one, your deaths and the time they cost, and a bar for enemy forces. The bar goes from green to yellow, orange and red as the upgrades slip away. Move it with /lock; turn each part on or off under /az -> Mythic+.",
					"A card when the key ends, showing your time against the limit, how many levels the keystone went up, your new rating and what it gained, and whether it was your best time in that dungeon. Click it to close it.",
					"Your keystone slots itself. Open the Font of Power and your key goes in. Untick /az -> Mythic+ -> Slot your keystone automatically to do it by hand.",
					"Great Vault progress on the info bar. \"Vault 2/9\" sits left of the latency and turns green when rewards are waiting; hover it to see each row and what the next slot needs. Turn it off under /az -> Info/Clock Settings.",
					"Pandemic timers on aura icons. On the player, target, group frames and nameplates, an aura's icon lights up gold for the last stretch in which recasting it loses nothing, the game's own pandemic window. Aura countdowns also change colour as they run out: yellow under 10 seconds, orange under 3, red at the end.",
					"Forever: dragging actions and flyouts are back. Forever 1.60.1.70009 fixed the game bug that stopped addons running secure code, so on that build and later you can drag spells onto and off the action bars again, open flyouts such as Mage portals, and use bar 1's vehicle exit. The chat message saying these were unavailable no longer appears.",
				},
			},
			{
				kind = "Development",
				items = {
					"Built the Mythic+ frame on the same data Blizzard's own tracker uses: the dungeon's world timer and time limit, the death count and the enemy forces criterion, so the numbers match the default tracker. The end-of-run card reuses the game's own completion wording, so it reads correctly in every language, and every value is checked before any arithmetic in case a later patch starts hiding it.",
					"Made the aura timers work within the new secret aura rules. The time left on an aura is hidden from addons in many places, so AzeriteUI hands the game a colour scale and the pandemic highlight and lets the game apply them, instead of reading the time itself.",
					"Traced the Forever fix to Blizzard's files. The newest Forever build changes the load order that had broken secure code since the beta began. AzeriteUI now checks each Forever build once, as it already does on Retail, and falls back to the old workaround if a later build breaks it again.",
					"Added an offline test for the Mythic+ features and the vault counter. It drives the real code through a key's stages, deaths, enemy forces, the end-of-run card, keystone slotting and the vault. It also showed that one of the existing checks had stopped running, which is fixed. These tests cannot show how anything looks in the game.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Verified offline only: none of this has been seen in the game yet. The Forever fix follows Blizzard's published files for build 70009.",
					"The Mythic+ frame, card and Great Vault counter are Retail only. Blizzard's own completion banner still shows next to the card, and clicking the vault counter does not open the Great Vault.",
					"Aura countdowns now use the game's number format, which may read slightly differently from before.",
					"The new option text was translated without native speakers; corrections are welcome on the Discord.",
				},
			},
		},
	},
	{
		version = "5.11.1-JuNNeZ",
		date = "2026-09-26",
		title = "Minions for Your Target, and No Names Over Corpses",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Minions only for your target. A new switch under /az -> Nameplates -> Visibility does for players' pets, totems and guardians what 5.11.0 did for friendly NPCs: friendly or enemy, they show a nameplate only while you target them, and tab-targeting an enemy pet counts. Ticking it turns on the game's Enemy minions and Friendly minions settings, which it needs. Both now also sit under /az -> Nameplates -> Game settings, so you can turn them off again there.",
					"No more names floating over corpses. Looting or skinning a dead enemy showed its name hanging over the body, because dead units have no nameplate to carry it. Untick /az -> Nameplates -> Game settings -> Your target's floating name to hide it. It is the game's own setting, one Blizzard's Options do not offer.",
				},
			},
			{
				kind = "Development",
				items = {
					"Found where the corpse name comes from. The game drops a unit's nameplate when it dies, so there is nothing for AzeriteUI to draw in its place. Going through the game's name settings on both clients turned up one that shows your target's name when no other setting would, and turning it off in game hid the corpse name; the new switch passes it straight through. Minions are recognised the way Blizzard's own nameplates recognise them, and the offline nameplate test covers both switches.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Your target's floating name is not limited to corpses: with it off, no target without a nameplate shows a name over it. A target with an AzeriteUI nameplate still shows its name on the plate.",
					"The new option text was translated without native speakers; corrections are welcome on the Discord.",
				},
			},
		},
	},
	{
		version = "5.11.0-JuNNeZ",
		date = "2026-09-26",
		title = "Friendly Nameplates Only for Your Target, and a Castbar That Steps Back",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Friendly nameplates only for your target. Two new switches under /az -> Nameplates -> Visibility: Friendly NPCs only for your target and Friendly players only for your target. With one on, a city full of vendors and quest givers shows no friendly plates until you click one. That one then gets its AzeriteUI nameplate instead of the game's floating name, and loses it when you target something else. The NPC your interact key would use shows its plate too. Ticking a switch also turns on the game's own Friendly NPCs or Friendly players setting, which it needs; unticking it leaves that setting as it is.",
					"The player castbar steps back when you are hit. When damage pushed a cast back, the red delay number appeared but the bar kept filling on the old schedule, sat full, and then waited for the spell to land. The bar now steps back on each hit as Blizzard's does, a channel that loses time shows it on the bar, and the delay number no longer counts earlier hits twice.",
					"Target portrait rotation no longer errors. A rotation set for the target frame's portrait raised a Lua error on every portrait update. No layout sets one by default, so most players never saw it.",
				},
			},
			{
				kind = "Development",
				items = {
					"Worked out why no setting could do this. Neither Retail nor Forever has a \"target only\" mode for friendly plates: the game makes a plate for every friendly NPC or for none, and with none, the NPC you click gets only its floating name. AzeriteUI now keeps the game making the plates and draws only the ones you target, through the same hidden state the plates already use when the game's own settings hide them. The offline nameplate test gained a step covering a vendor, a trainer, a friendly player and a follower companion through targeting, target switches, hovering, the interact key and objective bars.",
					"Fixed the castbar from a player's report on GitHub. The report traced the problem to the start and end times the bar is drawn from, which a pushback never updated, and a follow-up tested a fix in game on Forever that also rebuilds the bar's timer, since that client keeps the old span otherwise. AzeriteUI's change follows that report and the way Blizzard's own castbar recalculates on both clients. A new offline test drives the real castbar code through two pushbacks, a channel, an empowered cast and another unit's cast; the 5.10.2 code fails it with the reported symptoms.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Verified offline only: none of these changes has been seen in the game yet. The castbar fix matches one the reporter ran in game on Forever.",
					"A hidden friendly plate is still there, only invisible, so clicking just above an NPC's head can still select it.",
					"Blizzard's own NPC Names setting is separate. If names still float over friendly NPCs you have not targeted, turn them off in the game's Options under Nameplates.",
					"The new option text was translated without native speakers; corrections are welcome on the Discord.",
				},
			},
		},
	},
	{
		version = "5.10.2-JuNNeZ",
		date = "2026-09-25",
		title = "Tooltips That Line Up, and No Castbar Flicker",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Compare tooltips really stop overlapping. 5.10.1 said they no longer overlapped, but in the game they were still drawn edge to edge, one border running under the other. Shift-hovering an item now puts the tooltips side by side with every border whole and the \"Equipped\" tab still tucked behind it. The compare tooltips are also drawn at the same size as the tooltip they compare against, where they used to be slightly larger.",
					"Buff tooltips wear the AzeriteUI theme. Hovering the buffs at the top right, the aura row on the player frame or a nameplate aura showed Blizzard's default tooltip whatever the theme. Those tooltips now follow your Azerite or Classic theme, and go back to Blizzard's look when AzeriteUI's tooltip styling is switched off.",
					"Tooltip fixes you may notice. With /az -> Tooltips -> Show spellID on, hovering a buff or debuff raised a Lua error and showed no ID; IDs now show there, and on Blizzard's nameplate auras too. A unit's name is no longer written into a different tooltip than the one describing that unit, and a hidden name is no longer replaced with \"Unknown\". In combat inside instances, where the game hides a unit's health, the tooltip's health text now disappears instead of showing the previous unit's numbers.",
					"Hide in Combat reaches action buttons and unit frames. /az -> Tooltips -> Hide in Combat and its Hide ActionBar Tooltips in Combat and Hide UnitFrame Tooltips in Combat switches only ever affected the pet and stance bars. They now hide the tooltips of the action buttons and the unit frames in combat as well, and bring them back when it ends. Show Guildname, which never did anything, is gone.",
					"No more flicker under nameplates. Mousing over a nameplate or changing target could flash a gold bar under the health bar for a moment, sometimes carrying the name of a spell another mob had cast earlier. After a failed or interrupted cast, that bar could also come back for the rest of its brief hold. The castbar now appears only while the unit is casting.",
				},
			},
			{
				kind = "Development",
				items = {
					"Found out why the 5.10.1 compare fix did not hold, with a report built for it. /azdebug tooltips prints what AzeriteUI did to each compare tooltip and whether it was still in place a frame later. The first live report showed the spacing set and the tooltips drawn edge to edge anyway: either something positioned them again afterwards, or Blizzard's own top anchor won over the spacing. Which one is still open, and the fix does not depend on it. AzeriteUI now makes each join itself inside every call that positions a compare tooltip, whichever copy of Blizzard's code makes it. That needs no one-frame delay, which is what made the 5.3.5x attempt jitter. The offline tooltip test now repeats Blizzard's positioning the way the live client did, and both earlier versions fail it where the game showed the overlap.",
					"Audited the whole tooltip module against Blizzard's Retail 12.1 and Forever source. The buff tooltips turned out to be a protected Blizzard frame that addon code cannot touch, with one styling call Blizzard exports for it, which AzeriteUI now uses. The audit also turned up the Classic-only aura call behind the spell ID error, the nameplate aura tooltips that were never hooked, the name and health text faults, and settings nothing read. The offline tooltip test covers each of these, and the 5.10.1 module fails it in every one of those areas.",
					"Traced the nameplate flicker to AzeriteUI's own layout pass, which showed the castbar every time a plate was laid out, for the castbar code to hide again a frame later. The offline nameplate test hid such bars before every snapshot, so it could never see the flash. It now checks what is on screen before that frame, and checks that a plate hidden mid-cast shows its cast again when it comes back.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Confirmed in game on Retail: the compare tooltips with the Azerite theme, the buff tooltip theme, Show spellID, the unit name and the health text. Verified offline only: all of it on Forever, the compare tooltips with the Classic theme, Hide in Combat, and the nameplate castbar.",
					"If you ticked Hide in Combat earlier, action button and unit frame tooltips will now disappear in combat. Both of its switches start on; untick either one under /az -> Tooltips to keep those tooltips.",
					"If compare tooltips still overlap for you, type /azdebug tooltips straight after the shift-hover and post what it prints on the Discord.",
				},
			},
		},
	},
	{
		version = "5.10.1-JuNNeZ",
		date = "2026-09-25",
		title = "Action Bars Back on Forever, and Friendly NPCs Sized as Such",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Action bars are back on Forever. After the Forever 1.60.1.70009 client update every action bar could be missing, the pet and stance bars too, with 'for' limit must be a number errors from LibActionButton in BugSack. Going back to an older AzeriteUI did not help, because every version had the same flaw. The bars now load again. Retail was not affected.",
					"Friendly NPC size now reaches friendly NPCs. Most vendors, trainers and quest givers were sized as friendly players, so /az -> Nameplates -> Size -> Friendly NPC size (%) seemed to do nothing for them. NPCs are now told apart the way Blizzard's own nameplates do it, and the companions of follower dungeons count as players, as they do on Blizzard's plates. Friendly NPC size now starts at the friendly player size, so vendors look as they did until you change it.",
					"Blizzard's nameplate settings from inside AzeriteUI. /az -> Nameplates -> Game settings (it was Stacking) now also holds the game's own Always show nameplates, Enemies, Friendly players and Friendly NPCs switches; changing one there changes it in the game's Options, and AzeriteUI's plates follow at once. A new Position choice under Size puts plates over heads or at feet. Use Blizzard overall scale follows the game's Nameplate Size again, Medium matching 100%; it had stopped following anything.",
					"Compare tooltips no longer overlap. Shift-hovering an item, the AzeriteUI border covered the \"Equipped\" tab and overlapped the tooltip beside it. The borders now meet instead of overlapping, and the tab sits on top of the border, with both the Azerite and the Classic theme.",
					"Nameplate fixes you may notice. Blizzard's Simplified nameplate option no longer shrinks AzeriteUI's plates for friendly players and NPCs; the size settings decide. Changing Blizzard's nameplate size or style, or resizing the game window, no longer leaves the plates with Blizzard's spacing and click area until the next reload. Maximum distance now limits other players' plates too, and battlegrounds and arenas start at 60 yards so enemy players stay in range.",
				},
			},
			{
				kind = "Development",
				items = {
					"Traced the missing bars to one changed answer in the Forever client. The action button library looks for flyout spells by asking about every flyout number in turn, and counted on the game raising an error for a number that does not exist. Forever 70009 answers such a number with nothing instead, and that stopped the library before a single bar was built. The library now skips an empty answer as it skips an error, and does not look for flyouts on Forever at all, where AzeriteUI's own flyouts cannot open. A new offline test loads the whole library against four ways a client can answer; the old copy fails it with the reporter's exact two errors.",
					"Checked every nameplate setting against Blizzard's own Retail 12.1 and Forever code. That found the friendly NPC test Blizzard does not use, the Simplified option scaling AzeriteUI's plates from underneath, Blizzard resizing the plates over AzeriteUI's size, the friendly visibility settings under their old names, the Blizzard scale setting that no longer exists, and about ten settings AzeriteUI still wrote that the game no longer has. It now writes only settings the client has. Platynator and Plater were read for how they handle the same settings. The offline nameplate test now runs against the real 12.1 set and refuses any other, which the old test could not tell apart, and adds a vendor that cannot be assisted and a follower companion.",
					"Compare tooltips are spaced inside Blizzard's own layout call. An earlier attempt in 5.3.5x moved them a frame later, which made them jitter, and was removed. The gap is now added as Blizzard places them, from the width each theme's border really has, and the tab is tucked by the height measured from the border art. A new offline test measures the seam and the tab edge on both themes, either side, with one or two compared items.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Verified offline only: none of these changes has been seen in the game yet, on either client.",
					"In the open world, other players' plates now stop at your Maximum distance (40 by default) instead of the game's 60. Raise it under /az -> Nameplates -> Content settings if you want them farther.",
					"Near the right edge of the screen, a compare tooltip the game pushes back on screen may still overlap its neighbour by up to the border's width.",
					"The new option text was translated without native speakers; corrections are welcome on the Discord.",
				},
			},
		},
	},
	{
		version = "5.10.0-JuNNeZ",
		date = "2026-09-24",
		title = "Smarter Nameplates",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Nameplate auras stay through the whole fight, and you choose what they show. Auras that were on a nameplate before combat used to vanish during it and stay gone afterwards. Plates now draw their auras through Blizzard's own aura display, which keeps working in combat. /az -> Nameplates -> Aura filters picks the kinds: crowd control from anyone, your debuffs (optionally only the ones Blizzard highlights), important debuffs from other players, enemy buffs your group can dispel, purge or soothe, important enemy buffs such as big defensives, and your own short buffs on friendly plates.",
					"Nameplates can behave differently in each kind of content. /az -> Nameplates -> Content settings keeps its own maximum distance, faintest alpha and alpha behind walls for the open world, dungeons, Mythic+, raids, battlegrounds and arenas, and uses the one you are in. A Mythic+ key switches over when it starts, with no loading screen. The defaults are exactly the values used until now, so nothing changes until you change it.",
					"Two new aids for busy pulls, both off until you switch them on. Fade enemies fighting someone else (/az -> Nameplates -> Other fights) fades enemies that are in combat with no one in your group, so the pull you are in stands out; your target, focus and the plate under your cursor never fade. Show the execute marker (/az -> Nameplates -> Execute range) draws a line across enemy health bars at your execute threshold and tints the part of the bar below it once the enemy drops under it. The threshold follows your class and specialization, or can be set by hand where a talent moves it.",
					"Raid markers sit beside the health bar at a sensible size. Skulls and stars were drawn about three times the height of the bar, floating above the plate and climbing further as names and auras appeared. They now sit to the left of the bar, at size 28 by default, with Target marker size under Nameplates. The same page now also has Blizzard's own Stack enemy nameplates and Stack friendly nameplates switches, so they can be changed without leaving AzeriteUI.",
					"AzeriteUI is in the game menu. Escape now shows an AzeriteUI button under Options that opens the options window. Turn it off at /az -> Game Menu -> Show AzeriteUI in the game menu.",
					"Fixes you may notice. Interrupt colours on nameplate castbars now read your interrupt's cooldown correctly during combat, where they used to fall back to a guess, and a Warlock's pet interrupt now counts. A tab-targeted plate shows its name straight away. In a dungeon, changing any nameplate setting no longer put the plates back on open-world transparency until the next loading screen. Turning AzeriteUI's nameplates on or off now warns that it reloads the interface. With Platynator, Plater or another nameplate addon enabled, AzeriteUI's plates stand down without overwriting that addon's nameplate scale at every login, without reloading the interface each time a setting is changed, and the page says which addon is in charge. On Forever, Blizzard's own combo point dots no longer appear beside the hidden target frame.",
				},
			},
			{
				kind = "Development",
				items = {
					"Rebuilt the nameplate module in place rather than starting over, so the object-plate, soft-target and name-only fixes of earlier releases carry across. First an offline test was built that drives the real module through ten plates and a scripted session - targeting, focus, combat, zoning, reloads, recycled plates - and records every visible detail of every plate at every step, plus a count of how much work each step costs. Each change after that had to leave that record untouched, or change it only where intended. With that in place: about 650 lines of dead code went, nine defects were fixed (two of them caught by that record after reading the code had missed them), and the 3,900-line file became ten files with one job each.",
					"Nameplates do far less work. Target, focus and soft-target changes now touch only the plates whose state changed, instead of laying out every plate; two timers that ran twenty times a second for the whole session are gone, replaced by the events Blizzard's own nameplates use; and zoning no longer lays out plates that are about to be replaced anyway. Changing target with ten plates on screen went from about 530 widget calls to about 60.",
					"One interrupt check for nameplates and the target castbar. The two used to work out your interrupt separately, from different spell lists, and the nameplates read the cooldown in the one way that the game hides during combat. They now share one resolver that reads it the way combat allows, knows the Forever spell ranks, and watches your pet's casts as well as your own.",
					"Took work out of action bar key presses. A report of action bar keys that stop responding mid-fight came with an error showing the pet bar refreshing inside a key press, whenever a macro uses /petattack. That refresh now waits for the next frame, the fading library no longer re-checks every faded button each time one button registers, hotkey text is worked out once per key, and the stance bar gathers bursts of shapeshift events into one refresh. Before changing anything, AzeriteUI's action bars were compared with Bartender4, Dominos, ElvUI and the upstream action button library, to copy only what fits and leave alone what those projects had to roll back.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Tested in game on Retail: the rebuilt nameplate module, auras in combat, the raid markers and their slider, the aura filters, stacking and the game menu button. Verified offline only: content settings, the combat fading, the execute marker, the shared interrupt check, the nameplate-addon stand-down, the action bar changes and the Forever combo point fix. None of the nameplate work has been tried on Forever yet.",
					"The action bar changes remove AzeriteUI's own work from the key press; they are not yet confirmed to cure the unresponsive key. If it still happens, please report whether BugSack shows script ran too long.",
					"The execute marker is on nameplates only, not on the target frame.",
					"Forever nameplate auras drawn partly underneath the plate are not fixed in this release.",
				},
			},
		},
	},
	{
		version = "5.9.1-JuNNeZ",
		date = "2026-09-23",
		title = "The Tracker Switch Works, and Every Language Is Complete",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Hide the Blizzard Tracker now really hides it. On Forever the quest tracker came back after every login, reload and loading screen while /az -> Objectives Tracker -> Hide the Blizzard Tracker stayed ticked. On Retail the switch had never done anything at all. It now works on both, stays hidden through boss and arena encounters, and with the switch off the tracker still fades out during those encounters as before. If you ticked it once and forgot because nothing happened, your tracker will disappear after this update - untick it to bring the tracker back.",
					"AzeriteUI is fully translated in German, Spanish, French, Italian, Korean, Brazilian Portuguese, Russian and both Simplified and Traditional Chinese. The options window, its Settings tab, the preview messages, the day and night indicator and the Incoming Heals and Absorbs page had been English in every language. The heals and absorbs page and the power text and crystal colour choices under Unit Frames could not be translated at all, because their text was written straight into the page; now they read through the translation table like everything else.",
				},
			},
			{
				kind = "Development",
				items = {
					"Traced the tracker switch through Blizzard's own secure frame code. The switch sent its request to a kind of secure frame that only listens for state changes, so on Retail the request was never heard; on Forever a separate path did hide the tracker, and then the addon's own login handling faded it straight back in. Both now go through the single visibility rule that already handled bosses and arenas. A new offline test drives the real module through logins, reloads, loading screens, encounters, combat and Immersion dialogues on both clients. It failed the old code exactly where the report said, and passes the new one.",
					"Translations are now checked rather than hoped for. A new offline test loads every language file the way the game does and fails if a language is missing an English string, has an extra or duplicate one, leaves one empty, changes the placeholders a string is filled in with, or lets a preview line or tab label outgrow the options window. From now on, any new string has to arrive in all ten languages.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Verified offline only: neither change has been seen in the game on either client yet.",
					"The translations were written without native speakers, following each language's existing wording for nameplates, profiles and frames. Corrections are welcome on the Discord. Longer German and French lines are the most likely to crowd the options window at its smallest size.",
				},
			},
			{
				kind = "Internal",
				items = {
					"/azdebug keys bindings now shows what each key does right now and marks a key something else has taken, for the report of action bar keys that stop responding mid-combat.",
					"Removed the Export and Import Layout buttons that only appeared, permanently disabled, in the Development Mode mover options.",
				},
			},
		},
	},
	{
		version = "5.9.0-JuNNeZ",
		date = "2026-09-22",
		title = "A Solid Window, a Combat Queue and Settings That Ask First",
		groups = {
			{
				kind = "Highlights",
				items = {
					"The options window is solid, and its border is where a border should be. The background is fully opaque at 100% and thins out smoothly on the slider, which now moves a percent at a time rather than in five-percent notches. The sculpted edge is drawn the way AzeriteUI draws its own tooltips - same art, same weight, untinted - and it sits above everything the window holds, so no part of the header, list or footer is drawn over it any more.",
					"Settings changed in combat now really do wait for combat to end. The footer has promised this for several releases while the change went through immediately. It is a queue now: the setting keeps the value you chose, the row is marked, the footer counts what is waiting, and everything is applied the moment you leave combat - even if you closed the window in the meantime. The window's own appearance settings still apply at once, because they change nothing the game protects.",
					"Deleting a profile asks first. Delete Profile, Reset and importing settings each destroyed or overwrote something on a single click in the new window, with nothing asked. All three now confirm first, as they always did in the old dialog.",
					"A setting that refuses a value says why. Naming a new profile with an empty or duplicate name used to do nothing at all. The row now explains the refusal where its help text sits, and clears it as soon as the setting accepts what you typed.",
					"The window can be driven from the keyboard. Click the search box and press Tab to start: Tab and Shift-Tab move between settings, the arrows move within the list, Left and Right change a value, Enter does what a click does, typing searches, and Escape hands the keyboard back. Nothing is captured until you ask for it, so your movement and action keys keep working while the window is merely open.",
					"Panel Scale no longer fights the cursor. Dragging it rescaled the window under your mouse, so the slider slid away from the cursor and the value ran off. It now applies when you let go, while the slider itself still follows the cursor.",
				},
			},
			{
				kind = "Development",
				items = {
					"Measured the border art instead of guessing at it. The sculpted rim sits one to ten pixels into a side edge and eleven to nineteen into the top or bottom, which is why the old drawing let the background show past it. The casing now hangs outside the window by the same offsets the addon's tooltips use, with the fill tucked underneath, and the offline checks compare the panel's numbers against the tooltip's own layout data so the two cannot drift apart. The window's fill was also moved off Blizzard's tooltip background texture, whose opacity is not ours to control, onto one that takes exactly the alpha the slider asks for.",
					"Built the confirmation and refusal handling against the Ace3 library's own source rather than from an idea of how those fields work, because a text string in either of them means something different from what it looks like. Two cases deliberately fail safe: a confirmation the panel cannot work out is still asked, and a question that cannot be shown changes nothing.",
					"Added the three control types no setting in this addon uses yet - a colour swatch that opens the game's own picker, a keybinding button, and a multi-choice setting drawn as one toggle per option - together with a page to test them on, which appears only with Development Mode enabled. Adding any of these to a real settings page will now draw a working control instead of a blank space.",
					"Extended the offline checks to 527 for the panel and 186 deliberately broken versions, covering the border's layering, the combat queue, the keyboard, confirmations and refusals, the new control types and slider dragging. Five separate faults in the test scaffolding itself were found and fixed along the way, including one that had made every slider drag untestable. None of this emulates rendering, taint or protected execution in the game.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Tested in game on Retail, over a written checklist covering the window, the combat queue, confirmations, the keyboard, previews and a regression sweep. Not yet tested on Forever, and the new control types have not been exercised in game since the page for them was added.",
					"A change queued during combat is not saved anywhere until it is applied, so reloading the interface mid-combat discards it.",
					"Typing to search works while the keyboard is being used to walk the window, which is also when letters stop reaching the game, exactly as they do when any text box has focus. Press Escape to hand the keyboard back.",
					"Each theme still wears the same bronze casing; per-theme, per-class and per-race window art remains deferred.",
				},
			},
		},
	},
	{
		version = "5.8.0-JuNNeZ",
		date = "2026-09-22",
		title = "Quick Start, Truer Previews and Chattynator",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Chattynator's editbox position setting works again. AzeriteUI re-anchored the chat input line under its own chat window on every login and reload, overriding Chattynator's choice to put it at the top. With Chattynator enabled, AzeriteUI now leaves chat alone, as it already does for Prat, ls_Glass and BigInputBox. That also stops AzeriteUI from fading out the chat menu, channel and voice buttons Chattynator places in its own button bar, and from blanking and resizing the editbox artwork that Chattynator's Blizzard skin uses.",
					"/az now opens on Quick Start. A new first page in the Setup band gathers ten of the settings that change the most, from Explorer Mode and the action bars to nameplates, incoming heals and chat fading. Each one is still on its own page as well, and settings your client or character cannot use are left out.",
					"Everything you have changed, in one list. When any setting differs from its default, the header count (for example \"349 settings, 12 changed\") becomes a link. Click it to see every changed setting grouped by page and section; resetting one removes it from the list, and clicking the count again takes you back. The change markers and the count now update as soon as you change something, not the next time the panel opens.",
					"Live previews glow the frames a setting actually changes. Settings shared between frames used to flash the player frame. Incoming heal and absorb settings now glow every visible health bar, Color Cast Spell Text By State glows the target frame and nameplates, and page-wide action bar settings such as Hide Hotkeys glow every bar. Explorer Mode's timing and conditions glow the elements it fades, and nameplate size settings pick a plate of the right kind. When several frames glow, the footer counts them.",
					"When nothing on screen can show a change, the footer says why. Show Blizzard Raid Bar explains that the bar only appears in a party or raid, and Cast action keybinds on key down explains that it changes key presses rather than looks. Tooltip, world map, game menu and bag settings are outlined only while that window is open; otherwise the footer asks you to open it.",
				},
			},
			{
				kind = "Development",
				items = {
					"Audited every setting for what it changes on screen, not where it is saved. A setting records which profile stores it. For shared unit frame, action bar and Explorer Mode settings, that pointed the preview at one representative frame. The audit produced a table giving each such setting an exact frame, a family of frames or an explanation. A setting added later without an entry previews nothing rather than the player frame. Nameplate previews read only the flags the nameplate code already sanitises, never protected unit data.",
					"Built pages gathered from settings on other pages. Quick Start and the changed list draw each row from the setting's real location, with its own control, change marker and reset, and gather again on every refresh, so a reset setting drops out at once. Only the page that changed is recounted, so dragging a slider does not recount the whole panel.",
					"Extended the offline checks. The panel checks now cover the preview table (failing if an entry names a setting that no longer exists or drifts from Explorer Mode's own list), explanations fitting the footer at the smallest window, both new pages against the real Retail and Forever option tables, and live counts. Deliberately broken versions confirm the checks catch regressions. A new check covers the chat addon exclusion. None of this emulates rendering or protected execution in WoW.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Everything in this release is verified against source and offline checks only; nothing is confirmed in game yet. The Quick Start selection may still change.",
					"With Chattynator enabled, AzeriteUI's Chat options (fading and message timing) no longer apply and are left out of Quick Start; use Chattynator's own settings. Explorer Mode's chat fading does not reach Chattynator windows.",
					"Chattynator's social (Quick Join) button may still be hidden, because AzeriteUI hides Blizzard's micro buttons by default. Turning on Action Bars -> Micro Menu -> Show Blizzard's Micro Menu should bring it back; this is untested.",
				},
			},
		},
	},
	{
		version = "5.7.2-JuNNeZ",
		date = "2026-09-22",
		title = "Forever Combo Points, Take Two",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Forever Rogues and Druids now actually see their combo points. Forever hands combo points to addons as hidden (\"secret\") values, even out of combat, and AzeriteUI read them as zero, so the display never appeared. The game now fills the points directly: filled points are bright, empty sockets half-faded, the display is hidden with no points, and a full set still fades after combat unless Unit Frames -> Class Power -> Show Full Class Power Out of Combat is on. Retail is unchanged.",
				},
			},
			{
				kind = "Development",
				items = {
					"A player's /dump showed 5.7.1 had the cause wrong: the count was correct but secret, not zero. Each point now takes the secret value through its own range, and visibility comes from Blizzard's curve-based percent API, so addon code never reads or compares the number.",
					"Added an offline test that runs the real class power code against a stand-in secret value that fails on any arithmetic or comparison, plus deliberate-break checks proving each part of the fix is covered and Retail keeps its old path.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Verified offline only; not yet confirmed in game.",
					"With Class Power Click-Through turned off, the invisible zero-point display still blocks clicks in its area.",
				},
			},
		},
	},
	{
		version = "5.7.1-JuNNeZ",
		date = "2026-09-21",
		title = "Forever Combo Points",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Forever Rogues and Druids now see their combo points. Forever keeps classic combo points on the target, and the display was reading them the Retail way, so it always saw zero and stayed hidden. It now reads the points on your current target and updates when you change target. Retail is unchanged.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Fixed from Blizzard's Forever interface source and a player report; not yet confirmed in game.",
				},
			},
		},
	},
	{
		version = "5.7.0-JuNNeZ",
		date = "2026-09-21",
		title = "New Options, Predictions and Forever Fixes",
		groups = {
			{
				kind = "Highlights",
				items = {
					"The new options panel now opens with /az. It includes search, grouped navigation, changed-setting markers and individual resets. /az new remains an alias, /az classic keeps the previous skinned window, and /az legacy opens stock Ace3.",
					"Changed frame settings briefly identify their live frame with a golden glow. The preview never moves, resizes, shows or hides the target. When no usable frame exists, the panel explains that in its footer instead of drawing a simulated frame.",
					"Incoming heals and absorbs now use shaped overlays that fit AzeriteUI health bars. Under /az -> Unit Frames -> Incoming Heals and Absorbs, incoming heals, overheal cues, damage absorbs and healing absorbs can be controlled independently. Damage absorbs can show their total size or follow current health and incoming healing.",
					"Forever Druids can see combo points without a specific rank of Shred. Cat Form's Energy now gates the display on Forever, while Retail keeps its existing Shred requirement.",
					"Forever's day/night indicator has two artwork themes. Right-click the minimap indicator to choose between the existing Sky scenes and the supplied Sun & Moon artwork, alongside its saved distance control.",
					"Forever nameplate interrupt colors recognize classic spell IDs and ranks. Pummel, Kick, Silence, Earth Shock, Counterspell and pet Spell Lock use a Forever-specific resolver; Retail remains unchanged.",
				},
			},
			{
				kind = "Development",
				items = {
					"Moved the custom panel from preview to the normal settings route while preserving both fallbacks. Opening, closing and refreshing cover the new panel, retained window and stock dialog. The live-frame resolver handles numbered action bars, Explorer Mode elements, shared unit-frame settings and active AzeriteUI nameplates, with mutation-tested failure paths.",
					"Built an addon-owned health-prediction renderer around Blizzard's native measurement widgets. Fixed shaped artwork is revealed by masks while oUF retains event and lifecycle ownership, avoiding addon arithmetic on protected unit values. Separate caches preserve existing numeric absorb text and target-layout behavior.",
					"Expanded client-specific regression coverage. The panel, prediction geometry, Diel themes, real Retail and Forever option tables, client capability gates and deliberately broken variants are checked offline. Those checks do not emulate protected execution or GPU rendering in WoW.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"The retained options window remains at /az classic; deleting it is deferred by maintainer choice.",
					"Some policy settings do not own one visible frame. Show Blizzard Raid Bar and Color Cast Spell Text By State, for example, currently glow the player frame as the shared Unit Frames representative. More precise targets or explanatory previews are planned.",
					"Health-prediction rendering received live iteration for shield proportions, but the final overheal option, all frame families, combat behavior and Forever rendering still need broader in-game coverage.",
					"The Forever Druid combo-point gate and classic interrupt resolver pass offline checks but still need live class/rank testing. Forever action dragging, custom flyouts and Clique click-casting remain unavailable.",
				},
			},
		},
	},
}

-- Everything older is in CHANGELOG.md.
ns.ChangelogTotal = 28
