--[[

	The MIT License (MIT)

	Copyright (c) 2026 Jonas "JuNNeZ" Andersen

--]]
-- Generated by Tools/BuildChangelog.lua. Do not edit by hand.
--
-- The 12 most recent releases of 59 in CHANGELOG.md, which stays the
-- source of truth. Regenerate after editing it:
--
--     lua Tools/BuildChangelog.lua
local Addon, ns = ...

ns.Changelog = {
	{
		version = "5.6.0-JuNNeZ",
		date = "2026-09-20",
		title = "Forever and the New Options Panel",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Try the new options panel with /az new. Search across settings, browse grouped pages and sections, and see which supported settings differ from their defaults, with individual reset controls.",
					"Make the panel your own. Open /az new -> Settings -> Appearance for themes, background opacity, scale and position reset. Settings -> Changelog shows recent release notes in game.",
					"Forever action bars and group frames work around the beta's broken secure execution. Adds fallback paths for bar paging, visibility, player aura switching and party/raid frame setup, and avoids the startup probe that generated a Blizzard error.",
					"Forever's cog-wheel menu respects character unlocks and uses a compatible open/close path. The objective tracker also uses the beta-compatible visibility path.",
					"A day/night indicator for the Forever minimap. Drag it around the ring, right-click to adjust its distance, or turn it off under /az -> Minimap -> Day and Night Indicator to restore Blizzard's indicator.",
				},
			},
			{
				kind = "Access and beta limits",
				items = {
					"/az keeps the existing window; /az classic opens the stock Ace3 dialog. The new panel is an opt-in preview; later panel phases, including migration of /az, are deferred. Change frame settings outside combat.",
					"On the current Forever beta, action drag-and-drop, custom flyouts and Clique click-casting remain unavailable. Newly created group frames during combat finish setup after combat ends.",
					"Offline checks passed for both clients. Live /reload, combat and visual regression testing of this combined release is still needed.",
				},
			},
		},
	},
	{
		version = "5.5.0-JuNNeZ",
		date = "2026-09-19",
		title = "Retail and Forever",
		groups = {
			{
				kind = "Highlights",
				items = {
					"One download for Retail and WoW Forever. Adds the Forever beta load entry alongside Retail 12.1, with automatic client detection.",
					"Settings match your client. Forever omits arena frames, archaeology, the vehicle-seat display, specialization inspection and Retail-only class resources. Rogue and Druid combo points remain available. Unsupported settings are hidden in /az.",
					"The cog-wheel menu follows the client. Forever includes its Spellbook, Talents and Legacy buttons, while entries disabled by the game are omitted.",
					"Shared UI compatibility fixes keep modern aura safety, keybinding and dropdown behavior active on Forever despite its lower interface number.",
				},
			},
		},
	},
	{
		version = "5.4.13-JuNNeZ",
		date = "2026-09-17",
		title = "Friendly Names Closer to Their Heads",
		groups = {
			{
				kind = "Fixed",
				items = {
					"Friendly player names sit just above the character again. With names only turned on, player names floated well above heads, as if the hidden health bar and castbar still took up room. They now sit just over the head, and a bigger Friendly name size (%) makes the name grow upwards instead of down over the character. /az -> Nameplates -> Friendly Players -> Use names only for friendly players.",
					"Mailbox and other object names no longer show up oversized. They could appear at the larger friendly player name size when their nameplate had last shown a friendly player's name.",
				},
			},
		},
	},
	{
		version = "5.4.12-JuNNeZ",
		date = "2026-09-15",
		title = "An Aura Toggle for Raid Frames (5)",
		groups = {
			{
				kind = "Added",
				items = {
					"Raid Frames (5) can now hide their aura row. Since 5.4.11 the buffs you can apply and the debuffs you can dispel stay on these frames through combat, with no way to turn them off. Show Auras is on by default, so nothing changes unless you switch it off. Blizzard's boss mechanic icons in the middle of the health bar still show either way. /az -> Unit Frame Settings -> Raid Frames (5) -> Show Auras.",
				},
			},
		},
	},
	{
		version = "5.4.11-JuNNeZ",
		date = "2026-09-14",
		title = "Party Auras That Last Through Combat",
		groups = {
			{
				kind = "Fixed",
				items = {
					"Party frame auras no longer vanish the moment combat starts. Heal-over-time spells such as Rejuvenation, Regrowth and Lifebloom, along with the other buffs and debuffs on your party members, disappeared from the party frames as soon as a fight began and came back once it ended. The game no longer lets addons read aura data during combat, so the party aura row now uses the same game-driven aura display as the player and target frames, which keeps updating mid fight. Your own buffs are drawn first.",
					"Raid Frames (5) get the same fix. They show the buffs you can apply and the debuffs you can dispel, in and out of combat.",
					"\"Player / Self Buffs\" and \"Other Temporary Buffs\" now split by who cast the buff. With only \"Player / Self Buffs\" on, buffs other players put on you no longer slip in; with only \"Other Temporary Buffs\" on, those buffs now show instead of being hidden. /az -> Unit Frame Settings -> Player -> Player Aura Row, with Use AzeriteUI Stock Behavior off.",
				},
			},
			{
				kind = "Changed",
				items = {
					"The Party Aura Row options now pick from the game's own aura categories. Stock behavior shows your own castable buffs, dispellable, boss and other debuffs, and externals and raid buffs from other players. The custom toggles switch those categories on and off as before. \"Show Short Helpful Buffs\" on its own keeps your buffs to under a minute and \"Show Other Short Debuffs\" keeps other debuffs to about five minutes; stacks no longer count as short, and other players' buffs are no longer dimmed. /az -> Unit Frame Settings -> Party Frames -> Party Aura Row.",
				},
			},
			{
				kind = "Known limitations",
				items = {
					"The dispellable-debuff glow around a party frame and the priority-debuff icon in its middle still read aura data the old way, so they go blank during combat.",
					"Where the game keeps aura data secret, in dungeons and raids, changing Aura Size or Debuff Size % only reaches aura icons drawn after the change.",
				},
			},
			{
				kind = "Internal",
				items = {
					"/azdebug aurasnapshot party|raid5 and /azdebug unitmenu [trace on|off], for the combat aura and raid right-click menu reports.",
				},
			},
		},
	},
	{
		version = "5.4.10-JuNNeZ",
		date = "2026-09-13",
		title = "When Another Addon Styles the Game Menu",
		groups = {
			{
				kind = "Added",
				items = {
					"AzeriteUI now asks what to do when another addon restyles the game menu too. The menu you open with Escape could end up with two addons' looks stacked on top of each other. If W2UI, GW2 UI, FeelUI, DiabolicUI3, AddOnSkins or ConsolePort's menu is styling it as well, AzeriteUI asks the first time you open the menu in a session:",
					"AzeriteUI keeps AzeriteUI's look and turns the other addon off for this character.",
					"The other addon's name keeps its look and turns AzeriteUI's game menu style off.",
					"Blizzard turns both off and gives you the plain game menu.",
					"Decide Later changes nothing, and neither does pressing Escape.",
					"Change the game menu style whenever you like. /az -> Game Menu -> Game Menu Style lists the same choices and asks before reloading.",
				},
			},
		},
	},
	{
		version = "5.4.9-JuNNeZ",
		date = "2026-09-12",
		title = "A Dismount Button You Can Place",
		groups = {
			{
				kind = "Added",
				items = {
					"The dismount button can now have a position of its own. The round exit icon that shows up while you are mounted, in a vehicle or on a taxi normally rides the upper left of the minimap ring. Turn this on and it comes off the map, so you can put it anywhere on screen - useful if you have moved the minimap, replaced it with another addon's, or turned this one's minimap off entirely and been left with a button floating where the map used to be. Switch it back off and the button returns to the ring. /az -> Action Bars -> Dismount Button -> Use a custom position, then /lock to drag it into place and the mouse wheel over it to resize it.",
					"A dismount button you have placed yourself no longer hides with the minimap. Auto-hide takes the button along only while it is still sitting on the map ring, which was the point of hiding it in 5.4.8. Once it is somewhere else on screen it stays visible and clickable in arenas, battlegrounds and anywhere else the map hides itself - so you keep your click to dismount or to leave a battleground vehicle.",
				},
			},
		},
	},
	{
		version = "5.4.8-JuNNeZ",
		date = "2026-09-09",
		title = "The Dismount Button and the Empty Slots",
		groups = {
			{
				kind = "Fixed",
				items = {
					"Empty action bar slots no longer sit there at full brightness while the rest of the bar fades away. Slots you have not put anything on were being forced back to full opacity every time the UI reapplied your settings, which is why fading a bar appeared to fade only the buttons you actually use and leave a row of empty frames behind. Empty slots are now hidden by default, on every action bar, and they stay hidden through settings changes, mounting, vehicles and bar swaps.",
					"The dismount button now goes with the hidden minimap. The round exit icon that appears at the upper left of the minimap ring when you are mounted, in a vehicle or on a taxi is this UI's own button, and it hangs off the screen rather than off the map, so auto-hide never reached it and it sat there on its own. It now goes with everything else, and stops taking clicks while it is gone. Worth knowing: that button is how you click to dismount or to leave a battleground vehicle, so with the map hidden you will want your Dismount keybind or /leavevehicle instead. /az -> Minimap -> Auto-Hide, unchanged otherwise.",
				},
			},
			{
				kind = "Added",
				items = {
					"Show empty buttons. If you liked seeing the full grid on your action bars, turn it back on and the empty slots come back - and this time they fade along with the rest of the bar instead of staying put. /az -> Action Bars -> Show empty buttons. Off by default.",
				},
			},
		},
	},
	{
		version = "5.4.7-JuNNeZ",
		date = "2026-09-08",
		title = "The Blips the Hidden Minimap Left Behind",
		groups = {
			{
				kind = "Fixed",
				items = {
					"A hidden minimap no longer leaves your player arrow and your group's dots floating on an empty screen. Auto-hide faded out the map and everything sitting on it, but the game paints the player arrow, the party and raid dots and the tracking icons over the map rather than inside it, and those ignore transparency entirely. The map is now taken off screen outright while auto-hide has it hidden, which takes its blips with it. Nothing about the option itself changes - /az -> Minimap -> Auto-Hide works exactly as before, and the map still comes straight back when you leave.",
				},
			},
		},
	},
	{
		version = "5.4.6-JuNNeZ",
		date = "2026-09-08",
		title = "A Minimap That Gets Out of the Way",
		groups = {
			{
				kind = "Added",
				items = {
					"The minimap can now hide itself in the content you choose. Switch on /az -> Minimap -> Auto-Hide -> Hide the Minimap Automatically, then tick where it should disappear: Arenas, Battlegrounds, Dungeons or Raid Instances. Arenas and battlegrounds are ticked to begin with, so the common case takes a single click. The map comes back the moment you leave, and stays on screen while the frame mover is open so you can still position it. Off by default - nothing changes until you turn it on.",
					"Auto-hide covers the minimap and everything sitting on it, addon minimap buttons included. The clock and coordinate panel is a separate frame under /az -> Info and stays where it is.",
				},
			},
		},
	},
	{
		version = "5.4.5-JuNNeZ",
		date = "2026-09-06",
		title = "Less Work on Every Target Swap",
		groups = {
			{
				kind = "Fixed",
				items = {
					"Changing targets in a raid no longer rebuilds the target aura row from scratch. A boss and an ordinary target differ only in how wide that row is and how many icons it holds, but every swap between the two also re-applied the row's anchors, all seven of its group layouts and its filters, and that last step makes the game re-evaluate every aura on the spot. Those steps now run only when something they depend on actually changes, so retargeting in a raid does less work each time. Nothing about the row you see changes.",
				},
			},
			{
				kind = "Internal",
				items = {
					"The aura access guard added in 5.4.4 now falls back to C_Secrets.ShouldAurasBeSecret where the per-object access query is unavailable, so it fails closed instead of open. No behaviour change on a current client.",
					"/azdebug aura snapshots list helpful auras again. The debug code kept a private copy of the aura group list that stopped matching the six helpful groups the player row registers, and had been quietly dumping harmful auras only. It now reads the list the containers actually register.",
				},
			},
		},
	},
	{
		version = "5.4.4-JuNNeZ",
		date = "2026-09-06",
		title = "The Raid Freeze on Target Auras",
		groups = {
			{
				kind = "Fixed",
				items = {
					"The UI no longer locks up when you change targets in a raid. Switching between a boss and anything else rebuilds the target's aura row, and in a raid that rebuild threw an error part-way through. Because it never finished, the next target change started it over and threw again, so it compounded with every swap - at its worst on a boss reset, when the whole raid retargets at once. Target auras now leave those icons alone in content where the game keeps aura information private.",
				},
			},
			{
				kind = "Known limitation",
				items = {
					"In a raid, the player aura brightness toggle only reaches icons drawn after you change it. The game will not let us restyle an aura icon that is already on screen there, so /az -> Unit Frame Settings -> Player -> Player Aura Row -> Always Show Full Brightness may not take hold until those icons are redrawn. Everywhere else it applies at once, as before.",
				},
			},
		},
	},
}

-- Everything older is in CHANGELOG.md.
ns.ChangelogTotal = 59
