--[[

	The MIT License (MIT)

	Copyright (c) 2026 Jonas "JuNNeZ" Andersen

--]]
-- Generated by Tools/BuildChangelog.lua. Do not edit by hand.
--
-- The 12 most recent releases of 49 in CHANGELOG.md, which stays the
-- source of truth. Regenerate after editing it:
--
--     lua Tools/BuildChangelog.lua
local Addon, ns = ...

ns.Changelog = {
	{
		version = "5.20.1-JuNNeZ",
		date = "2026-10-10",
		title = "Legacy Keybinds and Proc Highlights",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Keybinds are back on Legacy action buttons. Under /go legacy the hexagonal button casing was drawn over the keybind text, stack counts and spell activation (proc) highlights, so hotkeys vanished and procs barely showed. The casing now sits beneath them, on action, pet, stance and extra buttons.",
					"Proc highlight options work under Legacy. With the highlight no longer hidden, style, colour source, colour and opacity under /az → Action Bars → Proc Highlight take effect. Thickness is hidden while Legacy is active, because Legacy draws every proc style with its own square highlight.",
				},
			},
			{
				kind = "Development",
				items = {
					"AzeriteUI's own copy of LibSharedMedia is now the latest version, the same one the published download already carried, so local builds match what players run. That version reports addons that register fonts or sounds that don't exist; AzeriteUI's own 50 media files were checked and all exist.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Offline-tested only; not yet confirmed in game.",
					"If another addon registers a missing font or sound, LibSharedMedia now reports it as an error naming that file. The fix belongs to the addon that registers it.",
				},
			},
		},
	},
	{
		version = "5.20.0-JuNNeZ",
		date = "2026-10-10",
		title = "Target Execute Marker and Cooldown-Ready Alerts",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Execute marker on the target frame. Turn it on under /az → Unit Frames → Target → Execute range: a line marks your execute threshold on the target's health bar, and the part below it turns red once the target drops into range. It follows every target tier (normal, elite, boss, critter, and the SaiyaRatt art), hides on friendly or non-attackable targets, and shares its threshold with the nameplate marker, so Automatic (your class and spec's execute) or By hand set on either page moves both. Off by default.",
					"Cooldown-ready alerts in the Cooldown Manager. Under /az → Cooldown Manager → Cooldown-ready alerts, choose Essential and/or Utility cooldowns and their icon flashes gold around its whole casing the moment the cooldown comes back, with an optional sound. It only fires on a cooldown you actually watched recover, never at login, on the global cooldown, or for an icon that was already ready. Off by default; it needs AzeriteUI's Cooldown Manager styling.",
				},
			},
			{
				kind = "Development",
				items = {
					"Both features were built to work with Retail 12.1's hidden combat numbers. The execute marker hands Blizzard's own health curve to the red zone instead of reading the target's health, and the alerts watch a hidden copy of each cooldown rather than reading cooldown times. Where a client lacks what either needs, the option is greyed out with an explanation and nothing is built.",
					"The alert flash was redone twice after in-game reports that it was too faint, and spells that can hold charges now alert when their ordinary cooldown recovers. The /azdebug cdready probe on the Debug tools page was used on Retail to compare how a spell's cooldown is reported in and out of combat.",
					"New offline test suites cover the execute marker on every tier and fill direction and the alerts across both cooldown viewers, charge spells, combat and cleanup, including runs that simulate a tainted caller. Ten new strings are translated in all ten languages.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Offline-tested. The alert flash and charge-spell recovery were seen live on Retail during development; the finished features still need a full in-game pass on Retail and Forever.",
					"Alerts are for an ordinary cooldown coming back, not for each charge of a multi-charge spell.",
				},
			},
		},
	},
	{
		version = "5.19.3-JuNNeZ",
		date = "2026-10-10",
		title = "Aura Size, Target Power and SaiyaRatt Imbues",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Smaller aura icons no longer overlap. Setting the target's aura size below about 34 under /az → Unit Frames → Target left the icons at their default size while spacing them for the smaller one, so they piled on top of each other, and icons added later could come out a different size. Every icon now follows the size you pick, on the target, the player row and group frames.",
					"Auras per row works on the target. The setting had no effect on Retail's target auras; it now limits each row to the number you choose. 0 still fills the frame's width.",
					"Aura timers fit small icons. Duration and stack numbers now shrink with the icon instead of spilling over their neighbours. The default size looks the same as before.",
					"Legacy target power bar shows its fill again. Under /go legacy the target's power bar showed only its dark background; the coloured fill was hidden underneath it.",
					"Weapon enchants on the SaiyaRatt profile. Imbues, poisons and oils now show in the SaiyaRatt player aura row too, as they do on the standard player frame.",
				},
			},
			{
				kind = "Development",
				items = {
					"The aura problems came from buttons being sized once, at creation, from the layout default while the chosen size only reached their placement. Sizes now flow through to every button and text, and the offline aura tests cover size, per-row width and text size.",
					"Fixing a Debug tools page error (a test status line formatting a missing spell ID) let the options panel test run in full again; it then showed that Extra Button Shape had no preview, which it now has.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Offline-tested only; not yet confirmed in game. SaiyaRatt's player auras still use the standard filtering, as before.",
				},
			},
		},
	},
	{
		version = "5.19.2-JuNNeZ",
		date = "2026-10-10",
		title = "Legacy HUD Repairs and a Full Profile Reset",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Switching to Legacy no longer erases your Azerite action bar settings. On Retail, going to /go legacy and back could silently reset bar fading, bar direction and bar anchors in your normal layout to their defaults. It no longer does. Settings already lost this way have to be set once more under /az → Action Bars.",
					"Legacy keeps its own minimap and cast bar spots. Moving the minimap or the cast bar under Legacy no longer changes where they sit in your Azerite layout, and both now start in their original 3.x places (minimap top right, cast bar bottom centre).",
					"The Legacy minimap shows its own ring. It was drawing the Azerite ring art shrunk inside the map; the old Legacy stone ring now sits around the map edge.",
					"Cleaner Legacy unit frames. The target portrait (the 3D model as well as the flat picture) no longer peeks out under the target frame; Target, Target of Target, Focus and Boss show their names again; the small frames get the 3.x hex casing without the dark square corners.",
					"Cast bar. Fishing, channels and casts that can't be interrupted no longer show a stray casing poking out of the Legacy cast bar.",
					"Minimap Enable works straight away. If the minimap was turned off when you logged in, switching /az → Minimap → Enable on now applies at once instead of after a reload.",
					"Profiles → Reset now really resets everything. It also clears settings kept for modules that were not loaded at the time (such as Legacy's own layout) and this character's own choices (theme, Lite+, Mage crystal, addon conflict and game menu picks), then reloads so every page shows its defaults. Account-wide settings, game options and your Edit Mode layout are left alone. The confirmation now says plainly that everything goes back to default.",
				},
			},
			{
				kind = "Development",
				items = {
					"The action bar and minimap problems were traced through the saved settings themselves: comparing saves before and after a Legacy round trip showed the lost values were exactly those that matched Legacy's defaults. The cause was Retail's delayed start for the action bars and minimap, which bypassed Legacy's separate settings.",
					"Legacy's offline tests now load that Retail start-up code directly, and also cover the portrait, names, casing sizes, cast bar and cast bar position (76 checks). The tests also exposed and fixed a Lua error Legacy would have raised for a module that had never saved settings, such as on a fresh install.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Offline-tested. The causes were confirmed with live readouts and saved settings from Retail; the fixes themselves still need checking in game, and on Forever.",
					"The full reset is offline-tested only; it has not yet been run in game.",
				},
			},
		},
	},
	{
		version = "5.19.1-JuNNeZ",
		date = "2026-10-10",
		title = "Legacy Portrait and Minimap Fixes",
		groups = {
			{
				kind = "Highlights",
				items = {
					"No more stray portrait under the Legacy target frame. When a target's 3D model was not ready yet, AzeriteUI showed a flat picture of the target instead, and Legacy did not hide it. It is now hidden along with the model.",
					"Turning the minimap back on brings the AzeriteUI minimap back. If you had used Restore Blizzard Default (for example while running another minimap addon), switching /az → Minimap → Enable back on kept Blizzard's look, and the page had no way to change it. Enable now restores the AzeriteUI look. This affected every layout, not just Legacy. Without updating, /setminimaptheme azerite does the same.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Offline-checked only; not yet confirmed in game.",
					"Two more Legacy reports are still under investigation: an extra background showing around the cast bar, and the target-of-target frame's background.",
				},
			},
		},
	},
	{
		version = "5.19.0-JuNNeZ",
		date = "2026-10-09",
		title = "Legacy HUD, Button Shapes and Debug Tools",
		groups = {
			{
				kind = "Highlights",
				items = {
					"The original compact AzeriteUI / GoldpawUI look is back as the Legacy HUD. Type /go legacy out of combat to switch, /go azerite to return, /go status to check; switching reloads. You get rectangular unit bars instead of the crystal and orb, rounded square buttons with the hexagonal casing that lights up on hover, the old minimap ring, aura borders and combat icon. You can also choose it on the Themes page once it is active.",
					"Your normal layout is left alone. Legacy keeps its own saved positions. By default the minimap sits top right with its text and widgets underneath, the buff row beside it, and tooltips, durability and vehicle seat in their old spots. Move anything you like; going back with /go azerite restores your Azerite profile exactly as it was.",
					"Square and rounded buttons. Every action bar, the pet bar and the stance bar has a Button Shape choice (Circle, Rounded, Square) under /az → Action Bars, and the extra action and zone ability buttons have Extra Button Shape. Circle stays the default; a change asks you to reload. Spacing is unchanged, and pet and stance buttons are scaled to their smaller size.",
					"/azdebug now opens a Debug tools page in the /az window. Five sections (Cooldown tests, Health and unit frames, Keybindings, Raid utility bar, Utilities) replace the crowded old debug popup. Debug output goes to the _DebugLog addon's AzeriteUI tab when it is installed, and to chat otherwise. Development Mode is required for most tools.",
				},
			},
			{
				kind = "Development",
				items = {
					"Legacy is a port of the AzeriteUI 3.x layout onto today's code, not a reinstall of the old addon. Its sizes, art and positions come from the 3.x source and its art is used with separately granted permission. Today's unit frames, health prediction, auras and secure action paging keep running underneath. Every 3.x Legacy layout setting and texture was audited against the port. Chat and tracker placement, the old pull-out bar panels, faster fading and the split aura filters were left out on purpose, as layout or behaviour rather than look.",
					"Legacy layouts live in separate saved settings per module. Your usual choices, such as aura filters and text, carry over once; positions never do. Hunter, Mage and Paladin theme art and Lite+ effects stand aside while Legacy is on.",
					"The button shape art and sizing are shared by all button types and scale to each button's cell, so the Circle look and spacing are untouched.",
					"The Debug page's cooldown tests compare several cooldown sources for one spell through a real recovery, to investigate spells whose ready state Blizzard reports inconsistently. Start, status and stop work in combat; they never cast anything.",
					"Offline harnesses cover the Legacy layout and profile isolation, the shape sizes, and the Debug page's controls, combat gating and log routing.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Everything here is offline-tested only. Legacy rendering, the shapes' fit in game and the Debug page still need live confirmation on Retail and Forever.",
					"Nameplates keep their modern look under Legacy. The tracker (Edit Mode) and chat stay where you put them.",
					"Legacy is for the main AzeriteUI profile; it refuses to switch on while a variant such as SaiyaRatt is selected, and never in combat.",
				},
			},
		},
	},
	{
		version = "5.18.2-JuNNeZ",
		date = "2026-10-09",
		title = "Imbue Tooltip Taint Fix",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Hovering a weapon imbue icon no longer raises a taint error. On Forever, the imbue icons added in 5.18.1 showed their tooltip in a way the client refused (\"Anchoring disallowed ... UntrustedLayoutScriptExecution\"). The tooltip is now anchored to the screen at the icon's top-left corner, so it sits slightly differently from before.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Offline-checked only; not yet confirmed in game. Retail is unchanged.",
				},
			},
		},
	},
	{
		version = "5.18.1-JuNNeZ",
		date = "2026-10-08",
		title = "Shaman Imbues on Forever",
		groups = {
			{
				kind = "Highlights",
				items = {
					"WoW Forever: Shaman imbues now show in the player aura row. Flametongue, Windfury, Rockbiter and other weapon imbues get their own icon at the start of the row, with a countdown, charges and the weapon tooltip, even while you have a target. In 5.18.0 Forever showed only oils and stones there. Show Weapon Enchants and Show Debuffs Only control them too.",
				},
			},
			{
				kind = "Development",
				items = {
					"On Forever an imbue is its own enchant type that Blizzard's aura container never receives. Several current Forever addons draw imbues themselves for the same reason. The row now reads every weapon enchant through Forever's own API and draws AzeriteUI icons for the ones the container leaves out, skipping the oil it already shows. Every value is checked for secrecy before use, and anything unreadable is skipped. The offline harness gained a Forever section, including fake secret values and three more deliberately broken copies.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Offline-tested only; not yet confirmed in game on Forever. If you recast an imbue in combat, its icon updates at once, but the row only makes room for it when combat ends. Imbue icons have no right-click cancel, and the top-right buff list still cannot show Forever imbues. Retail is unchanged.",
				},
			},
		},
	},
	{
		version = "5.18.0-JuNNeZ",
		date = "2026-10-08",
		title = "Weapon Enchants on the Player Aura Row",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Weapon enchants now show in the aura row above your health bar. Shaman imbues such as Flametongue, Rogue poisons, oils and whetstones appear right after your debuffs, with their timer, even while you have a target. Before, they only appeared in the top-right buff list, which hides while you have a target and fades out unless you hover it. Turn them off with /az → Unit Frames → Player → Show Weapon Enchants. The setting applies at once, with no reload. Show Debuffs Only hides them too.",
					"/azdebug aurasnapshot topright works again. It now reads the current top-right list, including its weapon-enchant buttons and the fade and visibility settings, instead of always reporting zero buttons. The aura snapshots no longer raise \"boolean test on a secret boolean value\" on Blizzard's aura buttons.",
				},
			},
			{
				kind = "Development",
				items = {
					"Weapon enchants are not auras, so no buff filter could ever include them. The row now registers Blizzard's own item-enchantment slots on its player container. Retail 12.1.0 cannot remove a slot once added, so turning the option off swaps the row to a second container without slots; 12.1.5 and Forever switch the slots off in place. A new offline harness checks both shapes, combat deferral and the vehicle row, and is itself tested by ten deliberately broken copies.",
					"The investigation started from a player report (Shaman, Flametongue not visible). It confirmed that the row's other filters work as designed: buffs longer than five minutes or without a timer stay in the top-right list in stock mode.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"The enchant icon and the top-right snapshot were confirmed live on Retail. Turning the option off and on without a reload, Show Debuffs Only and everything on Forever are offline-tested only. On Forever it is not yet known whether Blizzard's container receives Shaman imbues at all.",
					"The Player Alternate frame (SaiyaRatt profile) does not show weapon enchants yet.",
				},
			},
		},
	},
	{
		version = "5.17.2-JuNNeZ",
		date = "2026-10-07",
		title = "Pet Health Background and Edit Mode Fixes",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Pet health loss now has a dark background, matching the other unit frames instead of showing the world through the empty part of the bar.",
					"Blizzard's replaced party, raid, arena and personal-resource previews no longer show in Edit Mode. Their selection outlines and checkboxes are hidden too, including arena member debuff icons and cast bars. The minimap and Vehicle Exit button selection outlines are hidden as well.",
					"AzeriteUI stops adding power-update events to Blizzard's alternate power bar, avoiding the nil maximum-power error reported when the counter is not initialized.",
				},
			},
			{
				kind = "Development",
				items = {
					"Edit Mode suppression uses post-hooks and alpha-only hiding, restoring preview alpha on exit without changing Blizzard's Edit Mode registry. /azdebug editmode reports preview, overlay, checkbox and arena-member state. The Elune harness checks that the selection hook leaves the registry untouched.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Edit Mode hiding was confirmed live on Retail 12.1; Forever is not yet confirmed. The pet background and alternate-power change have not yet been confirmed in game.",
				},
			},
		},
	},
	{
		version = "5.17.1-JuNNeZ",
		date = "2026-10-06",
		title = "Pet Bar Keybinds Actually Cast",
		groups = {
			{
				kind = "Highlights",
				items = {
					"Pet action bar keybinds now cast the ability instead of doing nothing. Pressing a keybind on a pet bar button (reported on Warlock) silently toggled autocast instead of using the action, so most presses appeared to do nothing even though the correct keybind was shown on the button. Mouse clicks on the pet bar were unaffected. Left-click and the assigned keybind now behave the same.",
				},
			},
			{
				kind = "Development",
				items = {
					"Root cause: pet buttons use Blizzard's own PetActionButtonTemplate, whose click handler only calls CastPetAction when the click's button name is literally \"LeftButton\" and otherwise calls TogglePetAutocast. The pet bar's keybind-to-click simulation used a virtual \"Keybind\" button name (the convention our LAB-driven action and stance bars use, where it is recognized and mapped back to \"LeftButton\"), which Blizzard's plain pet button mixin does not recognize, so every keybind press fell into the autocast-toggle branch. Components/ActionBars/Elements/PetBar.lua's retail keybind path now simulates a \"LeftButton\" click for pet buttons specifically.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Verified offline (luac -p, lint). Live /reload confirmation of pet bar keybind casting on a pet class is still owed.",
				},
			},
		},
	},
	{
		version = "5.17.0-JuNNeZ",
		date = "2026-10-06",
		title = "Plays Nice with Other Addons",
		groups = {
			{
				kind = "Highlights",
				items = {
					"AzeriteUI asks which addon you want when ArcUI or BetterCooldownManager is enabled. Both restyle Blizzard's Cooldown Manager the same way AzeriteUI does, and two styles on the same icons do not work together. Until now AzeriteUI quietly stepped aside. A few seconds after login you now choose: AzeriteUI (turns the other addon off for this character and reloads), the other addon (AzeriteUI steps aside, no reload), Both (both keep styling, unsupported, reloads) or Decide Later. Change your answer under /az -> Cooldown Manager -> Choose again.",
					"CooldownManagerCentered and AzeriteUI's Cooldown Manager style now work together. Out of the box that addon only centres the rows, so AzeriteUI no longer steps aside for it.",
					"Baganator and BetterBags are left alone. While either is enabled AzeriteUI no longer moves Blizzard's bag slots, the same as with AdiBags, Bagnon and the other bag addons. The bag button beside the cog opens them as before.",
					"The info bar colours the zone name by PvP type on Forever too.",
					"The Hunter theme's protected-cast preview keeps its frame in /az -> Themes -> Bar tests, matching the 5.16.4 castbar fix.",
				},
			},
			{
				kind = "Development",
				items = {
					"Went through the roadmap's planned compatibility list against each addon's newest source. Only real clashes get the question, where the other addon changes the same frames in a way that breaks AzeriteUI's version; addons that only add tooltip lines (RaiderIO, ArchonTooltip) need nothing. Cell's newest release no longer ships a Retail or Forever version, and OmniCD's is still marked for an older game version on both clients, so neither needed a change. The question is a shared piece other features can use for future clashes.",
					"Action buttons, the chat setup at login and the keybinding mode's open-chat key now use the game's current functions instead of names that only exist while Blizzard's deprecation fallbacks are on. This also fixes range colouring for actions that check a specific unit.",
					"Regression tests cover the question's four answers, each answer being remembered or asked again, and which addons count as a clash.",
				},
			},
			{
				kind = "Access and known limits",
				items = {
					"Verified offline only; live confirmation on Retail and Forever is still owed, including each answer with ArcUI and CooldownManagerCentered with the Circular icon style.",
				},
			},
		},
	},
}

-- Everything older is in CHANGELOG.md.
ns.ChangelogTotal = 49
