param([switch]$Check)
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$name = 'AzeriteUI5_JuNNeZ_Edition'
$source = [IO.File]::ReadAllText((Join-Path $root "$name.toc"))
$expected = $source -replace '(?m)^## Interface:.*', '## Interface: 16001'
$expected = "# Generated by Tools/BuildClientTOC.ps1; edit the base TOC instead.`n## X-AzeriteUI-Client: Forever`n" + $expected
$expected = $expected.Replace("`r`n", "`n")
$target = Join-Path $root "${name}_Camelot.toc"
if ($Check) {
    if (-not (Test-Path -LiteralPath $target) -or [IO.File]::ReadAllText($target).Replace("`r`n", "`n") -cne $expected) {
        throw 'Forever TOC is out of date. Run Tools/BuildClientTOC.ps1.'
    }
} else {
    [IO.File]::WriteAllText($target, $expected, [Text.UTF8Encoding]::new($false))
}
