--[[

	The MIT License (MIT)

	Copyright (c) 2026 Jonas "JuNNeZ" Andersen

--]]
-- Turns CHANGELOG.md into Options/Changelog.lua, for the panel to read in game.
--
-- CHANGELOG.md stays the one source of truth: it is what CurseForge publishes
-- and what the release workflow edits. The game cannot read markdown, and the
-- whole file is over a hundred kilobytes, so the most recent releases are
-- written out as a Lua table and the rest stays in the file for GitHub.
--
-- Run it with the Lua 5.1 interpreter, from the addon root:
--
--     lua Tools/BuildChangelog.lua
--     lua Tools/BuildChangelog.lua --releases 20
--
-- It is not shipped; `.pkgmeta` ignores Tools/.

local RELEASES = 12
local SOURCE = "CHANGELOG.md"
local TARGET = "Options/Changelog.lua"

for i = 1, #arg do
	if (arg[i] == "--releases") then RELEASES = tonumber(arg[i + 1]) or RELEASES end
	if (arg[i] == "--source") then SOURCE = arg[i + 1] or SOURCE end
	if (arg[i] == "--target") then TARGET = arg[i + 1] or TARGET end
end

--------------------------------------------------------------------------
-- Markdown, reduced to what a FontString can say
--------------------------------------------------------------------------
-- No emphasis, no code spans, no links. The panel draws one font at one weight,
-- so the marks would show up as literal asterisks and backticks.
local Plain = function(text)
	text = text:gsub("%*%*(.-)%*%*", "%1")
	text = text:gsub("%*(.-)%*", "%1")
	text = text:gsub("`(.-)`", "%1")
	text = text:gsub("%[(.-)%]%b()", "%1")
	text = text:gsub("%s+", " ")
	return (text:gsub("^%s+", ""):gsub("%s+$", ""))
end

-- Lua's own quoting, so a release note containing a quote or a backslash cannot
-- break the file it is written into.
local Quote = function(text)
	return string.format("%q", text):gsub("\\\n", "\\n")
end

--------------------------------------------------------------------------
-- Reading
--------------------------------------------------------------------------
local source = io.open(SOURCE, "r")
if (not source) then
	io.stderr:write("could not open " .. SOURCE .. "\n")
	os.exit(1)
end

local releases = {}
local release, group, item

-- An item runs until the next bullet, heading or blank line, because a note
-- wraps across as many lines as it needs to in the file.
local CloseItem = function()
	if (item and group) then
		local text = Plain(table.concat(item, " "))
		if (text ~= "") then
			group.items[#group.items + 1] = text
		end
	end
	item = nil
end

for line in source:lines() do
	local version, date, title = line:match("^## ([%w%.%-]+) %((%d%d%d%d%-%d%d%-%d%d)%)%s*%-?%s*(.*)$")

	if (version) then
		CloseItem()
		release = { version = version, date = date, title = Plain(title), groups = {} }
		releases[#releases + 1] = release
		group = nil

	elseif (line:match("^## ")) then
		-- A heading that is not a release: the notes at the top of the file.
		CloseItem()
		release, group = nil, nil

	elseif (release) then
		local kind = line:match("^### (.+)$")
		local bullet = line:match("^%s*%-%s+(.*)$")

		if (kind) then
			CloseItem()
			group = { kind = Plain(kind), items = {} }
			release.groups[#release.groups + 1] = group

		elseif (bullet) then
			CloseItem()

			-- A release that starts listing before it names a section still has
			-- somewhere to put its notes.
			if (not group) then
				group = { kind = "", items = {} }
				release.groups[#release.groups + 1] = group
			end

			item = { bullet }

		elseif (item) then
			local continued = line:match("^%s+(%S.*)$")
			if (continued) then
				item[#item + 1] = continued
			else
				CloseItem()
			end
		end
	end
end

CloseItem()
source:close()

--------------------------------------------------------------------------
-- Writing
--------------------------------------------------------------------------
local kept = math.min(RELEASES, #releases)

local out = {}
local w = function(...) out[#out + 1] = table.concat({ ... }) end

w("--[[\n\n\tThe MIT License (MIT)\n\n\tCopyright (c) 2026 Jonas \"JuNNeZ\" Andersen\n\n--]]")
w("-- Generated by Tools/BuildChangelog.lua. Do not edit by hand.")
w("--")
w("-- The ", kept, " most recent releases of ", tostring(#releases), " in CHANGELOG.md, which stays the")
w("-- source of truth. Regenerate after editing it:")
w("--")
w("--     lua Tools/BuildChangelog.lua")
w("local Addon, ns = ...")
w("")
w("ns.Changelog = {")

for i = 1, kept do
	local r = releases[i]
	w("\t{")
	w("\t\tversion = ", Quote(r.version), ",")
	w("\t\tdate = ", Quote(r.date), ",")
	w("\t\ttitle = ", Quote(r.title), ",")
	w("\t\tgroups = {")

	for _, g in ipairs(r.groups) do
		if (#g.items > 0) then
			w("\t\t\t{")
			w("\t\t\t\tkind = ", Quote(g.kind), ",")
			w("\t\t\t\titems = {")
			for _, text in ipairs(g.items) do
				w("\t\t\t\t\t", Quote(text), ",")
			end
			w("\t\t\t\t},")
			w("\t\t\t},")
		end
	end

	w("\t\t},")
	w("\t},")
end

w("}")
w("")
w("-- Everything older is in CHANGELOG.md.")
w("ns.ChangelogTotal = ", tostring(#releases))
w("")

local target = io.open(TARGET, "w")
if (not target) then
	io.stderr:write("could not write " .. TARGET .. "\n")
	os.exit(1)
end

target:write(table.concat(out, "\n"))
target:close()

local items = 0
for i = 1, kept do
	for _, g in ipairs(releases[i].groups) do items = items + #g.items end
end

print(string.format("%s: %d of %d releases, %d notes", TARGET, kept, #releases, items))
